export const INSTRUCTORS = [
  { id: "alex", name: "Alex Chen", emoji: "👨‍💻", title: "Agent 架構師", bio: "前 Google 工程師，專注 AI Agent 系統設計，帶過 300+ 學員", avatar: "AC" },
  { id: "mia", name: "Mia Lin", emoji: "👩‍🏫", title: "Prompt 工程師", bio: "LangChain 貢獻者，擅長多模態 Agent 與 RAG 知識庫設計", avatar: "ML" },
  { id: "jason", name: "Jason Wu", emoji: "🧑‍🔬", title: "自動化專家", bio: "Make.com 認證顧問，幫 50+ 企業落地 AI 自動化流程", avatar: "JW" },
  { id: "sarah", name: "Sarah Ko", emoji: "👩‍💼", title: "商業化顧問", bio: "連續創業者，將 Agent 技術轉化為可變現產品的實戰專家", avatar: "SK" },
];

export const COURSES = [
  {
    id: "lv1",
    level: 1,
    emoji: "🥚",
    name: "孵化期",
    subtitle: "Agent 基礎入門",
    desc: "從零開始認識 AI Agent，學習 Prompt 設計、個性塑造與基本記憶機制。適合完全零基礎的新手。",
    price: 6800,
    modules: 10,
    color: "from-yellow-400 to-orange-400",
    instructor: "mia",
    schedule: [
      { date: "2026/07/05", time: "10:00–13:00", type: "live", topic: "開學典禮 × 什麼是 AI Agent", status: "upcoming" },
      { date: "2026/07/06", time: "10:00–13:00", type: "live", topic: "Prompt 設計基礎 × 角色塑造", status: "upcoming" },
      { date: "2026/07/12", time: "10:00–13:00", type: "live", topic: "記憶機制入門 × 工具呼叫", status: "upcoming" },
      { date: "2026/07/13", time: "10:00–13:00", type: "live", topic: "第一隻 Agent 誕生 × 實作", status: "upcoming" },
    ],
    recordings: [
      { title: "試聽課｜AI Agent 是什麼？", duration: "28:00", free: true },
    ],
    lessons: [
      { name: "什麼是 AI Agent", type: "核心概念" },
      { name: "Prompt 設計基礎", type: "進階心法" },
      { name: "Agent 個性塑造", type: "核心概念" },
      { name: "記憶類型總覽", type: "技術名詞" },
      { name: "工具呼叫入門", type: "核心概念" },
      { name: "零範例 vs 少量示例", type: "進階心法" },
      { name: "Chain-of-Thought 推理", type: "進階心法" },
      { name: "角色扮演設定", type: "進階心法" },
      { name: "輸出格式控制", type: "技術名詞" },
      { name: "第一隻 Agent 誕生", type: "實作項目" },
    ],
  },
  {
    id: "lv2",
    level: 2,
    emoji: "🐣",
    name: "成長期",
    subtitle: "技能模組整合",
    desc: "為 Agent 安裝真實可用的技能：網路搜尋、讀檔、寄信、行事曆、RAG 知識庫。全程直播實作。",
    price: 12800,
    modules: 10,
    color: "from-green-400 to-teal-400",
    instructor: "jason",
    schedule: [
      { date: "2026/07/19", time: "10:00–17:00", type: "live", topic: "搜尋技能 × Webhook × Make.com", status: "upcoming" },
      { date: "2026/07/20", time: "10:00–17:00", type: "live", topic: "RAG 知識庫建置 × LINE 推播", status: "upcoming" },
      { date: "2026/07/26", time: "10:00–17:00", type: "live", topic: "Email 自動化 × 行事曆整合", status: "upcoming" },
      { date: "2026/07/27", time: "10:00–17:00", type: "live", topic: "技能整合測驗 × 結業展示", status: "upcoming" },
    ],
    recordings: [
      { title: "試聽課｜RAG 知識庫是什麼？", duration: "35:00", free: true },
      { title: "回放｜Webhook 觸發機制（示範）", duration: "52:00", free: false },
    ],
    lessons: [
      { name: "網路搜尋技能", type: "工具/平台" },
      { name: "檔案讀取與分析", type: "技術名詞" },
      { name: "Email 自動寄送", type: "工具/平台" },
      { name: "Google 行事曆整合", type: "工具/平台" },
      { name: "RAG 知識庫建置", type: "核心概念" },
      { name: "Webhook 觸發機制", type: "技術名詞" },
      { name: "Make.com 自動化串接", type: "工具/平台" },
      { name: "LINE 訊息推播", type: "工具/平台" },
      { name: "結構化輸出 JSON", type: "技術名詞" },
      { name: "技能模組測驗", type: "實作項目" },
    ],
  },
  {
    id: "lv3",
    level: 3,
    emoji: "🐦",
    name: "訓練期",
    subtitle: "進階技能強化",
    desc: "深入 Agent 的規劃能力、多步驟執行、錯誤自修正與個性微調。大量真實案例直播演示。",
    price: 16800,
    modules: 8,
    color: "from-blue-400 to-indigo-500",
    instructor: "alex",
    schedule: [
      { date: "2026/08/02", time: "10:00–17:00", type: "live", topic: "ReAct 推理 × 多步驟任務規劃", status: "upcoming" },
      { date: "2026/08/09", time: "10:00–17:00", type: "live", topic: "工具鏈串接 × 錯誤自修正", status: "upcoming" },
      { date: "2026/08/16", time: "10:00–17:00", type: "live", topic: "Fine-tuning × Context 管理", status: "upcoming" },
      { date: "2026/08/23", time: "10:00–17:00", type: "live", topic: "Agent 壓力測試 × 結業", status: "upcoming" },
    ],
    recordings: [
      { title: "試聽課｜ReAct 思考模式解析", duration: "40:00", free: true },
    ],
    lessons: [
      { name: "多步驟任務規劃", type: "核心概念" },
      { name: "ReAct 推理模式", type: "核心概念" },
      { name: "工具鏈串接", type: "技術名詞" },
      { name: "錯誤自動修正", type: "核心概念" },
      { name: "個性微調 Fine-tuning", type: "技術名詞" },
      { name: "Function Calling 深入", type: "技術名詞" },
      { name: "Context 管理策略", type: "進階心法" },
      { name: "Agent 壓力測試", type: "實作項目" },
    ],
  },
  {
    id: "lv4",
    level: 4,
    emoji: "🦅",
    name: "進化期",
    subtitle: "多 Agent 協作",
    desc: "建立 Agent 團隊，學習多智能體協調、A2A 協議與任務調度。講師帶做真實多 Agent 系統。",
    price: 22800,
    modules: 8,
    color: "from-purple-500 to-pink-500",
    instructor: "alex",
    schedule: [
      { date: "2026/08/30", time: "10:00–17:00", type: "live", topic: "Multi-Agent 架構 × A2A 協議", status: "upcoming" },
      { date: "2026/09/06", time: "10:00–17:00", type: "live", topic: "CrewAI × 任務調度實作", status: "upcoming" },
      { date: "2026/09/13", time: "10:00–17:00", type: "live", topic: "MCP Server × 記憶共享", status: "upcoming" },
      { date: "2026/09/20", time: "10:00–17:00", type: "live", topic: "多 Agent 協作實戰 Demo", status: "upcoming" },
    ],
    recordings: [],
    lessons: [
      { name: "Multi-Agent 架構設計", type: "核心概念" },
      { name: "A2A 協議實作", type: "技術名詞" },
      { name: "CrewAI 框架入門", type: "工具/平台" },
      { name: "任務調度與分工", type: "核心概念" },
      { name: "Agent 間記憶共享", type: "技術名詞" },
      { name: "MCP Server 設定", type: "工具/平台" },
      { name: "Supervisor 模式", type: "核心概念" },
      { name: "多 Agent 協作實戰", type: "實作項目" },
    ],
  },
  {
    id: "lv5",
    level: 5,
    emoji: "🦁",
    name: "畢業期",
    subtitle: "部署 & 商業化",
    desc: "將訓練好的 Agent 打包成 Skill、上架技能市場、接案與變現。Sarah 親授商業變現實戰。",
    price: 19800,
    modules: 6,
    color: "from-red-500 to-yellow-500",
    instructor: "sarah",
    schedule: [
      { date: "2026/09/27", time: "10:00–17:00", type: "live", topic: "Skill 封裝 × API 對外開放", status: "upcoming" },
      { date: "2026/10/04", time: "10:00–17:00", type: "live", topic: "技能市場上架 × 定價策略", status: "upcoming" },
      { date: "2026/10/11", time: "10:00–17:00", type: "live", topic: "畢業 Demo 展示 × 接案實戰", status: "upcoming" },
    ],
    recordings: [
      { title: "試聽課｜Agent 如何變現？", duration: "32:00", free: true },
    ],
    lessons: [
      { name: "Agent 部署方式總覽", type: "技術名詞" },
      { name: "Skill 封裝打包", type: "核心概念" },
      { name: "API 對外開放", type: "技術名詞" },
      { name: "技能市場上架流程", type: "商業概念" },
      { name: "Agent 服務定價策略", type: "商業概念" },
      { name: "畢業 Demo 展示", type: "實作項目" },
    ],
  },
];

export const SKILLS = [
  { id: "web-search", name: "網路搜尋", emoji: "🔍", desc: "即時查詢網路資訊", category: "資訊取得", popular: true },
  { id: "rag-kb", name: "知識庫 RAG", emoji: "📚", desc: "連接私有文件知識庫", category: "資訊取得", popular: true },
  { id: "email", name: "Email 寄送", emoji: "📧", desc: "自動撰寫與寄送郵件", category: "溝通工具", popular: false },
  { id: "line", name: "LINE 推播", emoji: "💬", desc: "LINE 訊息自動推播", category: "溝通工具", popular: true },
  { id: "calendar", name: "行事曆管理", emoji: "📅", desc: "讀寫 Google 行事曆", category: "生產力", popular: false },
  { id: "sheets", name: "試算表讀寫", emoji: "📊", desc: "讀取與更新 Google Sheets", category: "生產力", popular: true },
  { id: "image-gen", name: "圖像生成", emoji: "🎨", desc: "文字轉圖片，視覺內容產出", category: "創意工具", popular: false },
  { id: "voice", name: "語音輸出 TTS", emoji: "🎙️", desc: "將回應轉為語音播放", category: "創意工具", popular: false },
  { id: "code-run", name: "程式執行", emoji: "💻", desc: "執行 Python/JS 程式碼", category: "開發工具", popular: true },
  { id: "browser", name: "瀏覽器操控", emoji: "🌐", desc: "自動操作網頁與抓取資料", category: "開發工具", popular: false },
  { id: "memory-long", name: "長期記憶", emoji: "🧠", desc: "跨對話記住用戶偏好", category: "記憶系統", popular: true },
  { id: "memory-short", name: "短期暫存", emoji: "💾", desc: "對話中暫存關鍵資訊", category: "記憶系統", popular: false },
  { id: "payment", name: "金流串接", emoji: "💳", desc: "處理付款與發票", category: "商業工具", popular: false },
  { id: "crm", name: "客戶管理", emoji: "👥", desc: "記錄與追蹤客戶互動", category: "商業工具", popular: true },
  { id: "scheduler", name: "排程觸發", emoji: "⏰", desc: "定時自動執行任務", category: "自動化", popular: false },
  { id: "webhook", name: "Webhook 接收", emoji: "🔗", desc: "監聽外部事件觸發", category: "自動化", popular: true },
];

export const TASKS = [
  {
    id: "t1",
    title: "電商客服 Agent 訓練",
    desc: "需要一個能自動回覆客訴、查詢訂單狀態的客服 Agent",
    difficulty: "初級",
    reward: 8000,
    points: 200,
    deadline: "2026/7/15",
    skills: ["email", "crm", "rag-kb"],
  },
  {
    id: "t2",
    title: "每日新聞摘要 Agent",
    desc: "每天早上 8 點自動搜尋科技新聞、整理摘要並推播到 LINE",
    difficulty: "中級",
    reward: 15000,
    points: 500,
    deadline: "2026/7/20",
    skills: ["web-search", "line", "scheduler"],
  },
  {
    id: "t3",
    title: "銷售 Agent 接案顧問",
    desc: "為保險業務員打造能自動生成提案書、追蹤客戶的 Agent",
    difficulty: "高級",
    reward: 45000,
    points: 1000,
    deadline: "2026/7/31",
    skills: ["memory-long", "crm", "email", "sheets"],
  },
  {
    id: "t4",
    title: "社群行銷 Agent",
    desc: "自動生成 IG/Threads 貼文、分析數據並建議最佳發文時間",
    difficulty: "中級",
    reward: 20000,
    points: 600,
    deadline: "2026/7/25",
    skills: ["image-gen", "web-search", "sheets"],
  },
];

export const REDEEM_ITEMS = [
  { id: "r1", name: "課程折抵券 NT$500", category: "課程折抵", points: 800, stock: 999 },
  { id: "r2", name: "Agent 優先訓練券", category: "訓練權益", points: 600, stock: 30 },
  { id: "r3", name: "技能包加速解鎖", category: "訓練權益", points: 1200, stock: 20 },
  { id: "r4", name: "1-on-1 Agent 諮詢 30 分鐘", category: "專屬服務", points: 2000, stock: 8 },
  { id: "r5", name: "VIP 學員一個月", category: "VIP 權益", points: 3000, stock: 5 },
  { id: "r6", name: "Agent School 馬克杯", category: "實體好禮", points: 900, stock: 25 },
  { id: "r7", name: "限量聯名T恤", category: "實體好禮", points: 1500, stock: 15 },
  { id: "r8", name: "Agent 機械鍵盤（限量）", category: "實體好禮", points: 6800, stock: 3 },
];

export const NAV_ITEMS = [
  { href: "/", label: "儀表板", emoji: "🏠" },
  { href: "/learning", label: "學習中心", emoji: "📖" },
  { href: "/training", label: "Agent 訓練所", emoji: "🎓" },
  { href: "/tasks", label: "任務中心", emoji: "💼" },
  { href: "/skills", label: "技能市場", emoji: "⚡" },
  { href: "/community", label: "交流中心", emoji: "💬" },
  { href: "/points", label: "我的點數", emoji: "🪙" },
  { href: "/redeem", label: "兌換中心", emoji: "🎁" },
  { href: "/messages", label: "訊息中心", emoji: "📩" },
];
