export type GuideFeature = { icon: string; text: string };
export type GuideStep = { icon: string; title: string; desc: string };

export type Guide = {
  emoji: string;
  title: string;
  tagline: string;
  /** 插畫 SVG（內嵌字串，viewBox 0 0 400 220） */
  svg: string;
  whatIs: string;
  features: GuideFeature[];
  steps: GuideStep[];
  /** 完整語音導覽稿（繁中口語） */
  voice: string;
};

/** 共用插畫底框：漸層背景 + 柔光，內容由 inner 填入 */
function scene(inner: string) {
  return `<svg viewBox="0 0 400 220" xmlns="http://www.w3.org/2000/svg" class="w-full h-auto">
    <defs>
      <linearGradient id="bg" x1="0" y1="0" x2="1" y2="1">
        <stop offset="0" stop-color="#1a1033"/><stop offset="1" stop-color="#0d0820"/>
      </linearGradient>
      <linearGradient id="pp" x1="0" y1="0" x2="1" y2="1">
        <stop offset="0" stop-color="#a855f7"/><stop offset="1" stop-color="#ec4899"/>
      </linearGradient>
      <linearGradient id="bl" x1="0" y1="0" x2="1" y2="1">
        <stop offset="0" stop-color="#6366f1"/><stop offset="1" stop-color="#22d3ee"/>
      </linearGradient>
    </defs>
    <rect width="400" height="220" rx="16" fill="url(#bg)"/>
    <circle cx="60" cy="40" r="70" fill="#a855f7" opacity="0.16"/>
    <circle cx="350" cy="200" r="80" fill="#ec4899" opacity="0.12"/>
    ${inner}
  </svg>`;
}

export const GUIDES: Record<string, Guide> = {
  "/": {
    emoji: "🏠",
    title: "儀表板",
    tagline: "你的學習與接案總覽，一眼掌握全局",
    svg: scene(`
      <rect x="150" y="44" width="210" height="34" rx="8" fill="url(#pp)" opacity="0.9"/>
      <rect x="160" y="54" width="90" height="6" rx="3" fill="#fff" opacity="0.9"/>
      <rect x="160" y="66" width="140" height="5" rx="2.5" fill="#fff" opacity="0.5"/>
      <g>
        <rect x="40" y="96" width="74" height="48" rx="10" fill="#fff" opacity="0.06" stroke="#a855f7" stroke-opacity="0.4"/>
        <rect x="124" y="96" width="74" height="48" rx="10" fill="#fff" opacity="0.06" stroke="#22d3ee" stroke-opacity="0.4"/>
        <rect x="208" y="96" width="74" height="48" rx="10" fill="#fff" opacity="0.06" stroke="#eab308" stroke-opacity="0.4"/>
        <rect x="292" y="96" width="68" height="48" rx="10" fill="#fff" opacity="0.06" stroke="#22c55e" stroke-opacity="0.4"/>
        <circle cx="58" cy="112" r="7" fill="#a855f7"/><circle cx="142" cy="112" r="7" fill="#22d3ee"/>
        <circle cx="226" cy="112" r="7" fill="#eab308"/><circle cx="310" cy="112" r="7" fill="#22c55e"/>
        <rect x="50" y="126" width="40" height="6" rx="3" fill="#fff" opacity="0.5"/>
        <rect x="134" y="126" width="40" height="6" rx="3" fill="#fff" opacity="0.5"/>
        <rect x="218" y="126" width="40" height="6" rx="3" fill="#fff" opacity="0.5"/>
        <rect x="302" y="126" width="36" height="6" rx="3" fill="#fff" opacity="0.5"/>
      </g>
      <g transform="translate(40,160)">
        <rect x="0" y="22" width="14" height="20" rx="3" fill="url(#pp)"/>
        <rect x="20" y="12" width="14" height="30" rx="3" fill="url(#pp)"/>
        <rect x="40" y="0" width="14" height="42" rx="3" fill="url(#pp)"/>
        <rect x="60" y="16" width="14" height="26" rx="3" fill="url(#bl)"/>
        <rect x="80" y="6" width="14" height="36" rx="3" fill="url(#bl)"/>
      </g>
      <text x="300" y="186" font-size="30">🚀</text>
    `),
    whatIs:
      "儀表板是你進入 Agent School 的第一站，把分散在各個功能裡的重點濃縮成一頁。它幫你回答三個問題：我學到哪了？我的 Agent 在做什麼？我離賺到錢還有多遠？不需要點來點去，打開就能掌握全局。",
    features: [
      { icon: "📊", text: "四大關鍵數據：學習天數、累積點數、已訓練 Agent、本月市場收益" },
      { icon: "🎥", text: "近期直播課一覽，紅點代表即將開課" },
      { icon: "🛒", text: "市場熱賣 Agent，看別人靠什麼賺錢" },
      { icon: "🔄", text: "Learn→Earn 飛輪，標出你目前走到哪一步" },
    ],
    steps: [
      { icon: "👀", title: "先看數據", desc: "上方四張卡掌握你的整體進度" },
      { icon: "🎓", title: "接著行動", desc: "點英雄區按鈕去訓練 Agent 或考證照" },
      { icon: "💰", title: "邁向變現", desc: "順著飛輪一路走到上架賺分潤" },
    ],
    voice:
      "歡迎來到儀表板，這裡是你的學習與接案總覽。最上方的英雄區，顯示你最近的學習進度，還有下一堂直播課的倒數。中間這四張卡片，是你最關鍵的數據：學習天數、累積點數、已經訓練好的 Agent 數量，以及這個月在市場上賺到的收益。再往下，你會看到近期的直播課程、市場上最熱賣的 Agent，還有你自己訓練的 Agent 目前的狀態。右邊那個飛輪，會帶你走完從學習、訓練、考證、上架，一直到賺取分潤的完整路徑。記住，畫面上幾乎每一張卡片都可以點，點下去就會直接帶你到對應的功能。",
  },
  "/profile": {
    emoji: "👤",
    title: "我的主頁",
    tagline: "我的 Agent、學習進度、證照牆與收益，一頁看清你的特工生涯",
    svg: scene("<rect x=\"40\" y=\"40\" width=\"320\" height=\"64\" rx=\"14\" fill=\"#fff\" opacity=\"0.05\" stroke=\"#a855f7\" stroke-opacity=\"0.35\"/>\n<rect x=\"54\" y=\"54\" width=\"36\" height=\"36\" rx=\"10\" fill=\"url(#pp)\"/>\n<text x=\"60\" y=\"80\" font-size=\"20\">🤖</text>\n<rect x=\"102\" y=\"58\" width=\"120\" height=\"8\" rx=\"4\" fill=\"#fff\" opacity=\"0.85\"/>\n<rect x=\"102\" y=\"74\" width=\"90\" height=\"6\" rx=\"3\" fill=\"#fff\" opacity=\"0.4\"/>\n<g transform=\"translate(238,52)\">\n  <rect x=\"0\" y=\"0\" width=\"50\" height=\"40\" rx=\"8\" fill=\"#fff\" opacity=\"0.05\" stroke=\"#22d3ee\" stroke-opacity=\"0.4\"/>\n  <rect x=\"58\" y=\"0\" width=\"50\" height=\"40\" rx=\"8\" fill=\"#fff\" opacity=\"0.05\" stroke=\"#22c55e\" stroke-opacity=\"0.4\"/>\n  <rect x=\"12\" y=\"10\" width=\"26\" height=\"7\" rx=\"3\" fill=\"#fff\" opacity=\"0.8\"/>\n  <rect x=\"14\" y=\"24\" width=\"22\" height=\"5\" rx=\"2\" fill=\"#fff\" opacity=\"0.4\"/>\n  <rect x=\"72\" y=\"10\" width=\"22\" height=\"7\" rx=\"3\" fill=\"#22c55e\" opacity=\"0.9\"/>\n  <rect x=\"72\" y=\"24\" width=\"22\" height=\"5\" rx=\"2\" fill=\"#fff\" opacity=\"0.4\"/>\n</g>\n<g transform=\"translate(40,120)\">\n  <rect x=\"0\" y=\"0\" width=\"190\" height=\"80\" rx=\"12\" fill=\"#fff\" opacity=\"0.05\" stroke=\"#a855f7\" stroke-opacity=\"0.3\"/>\n  <rect x=\"14\" y=\"14\" width=\"28\" height=\"28\" rx=\"8\" fill=\"url(#pp)\"/>\n  <text x=\"19\" y=\"34\" font-size=\"15\">🤖</text>\n  <rect x=\"52\" y=\"18\" width=\"70\" height=\"7\" rx=\"3\" fill=\"#fff\" opacity=\"0.85\"/>\n  <rect x=\"52\" y=\"31\" width=\"100\" height=\"5\" rx=\"2\" fill=\"#fff\" opacity=\"0.4\"/>\n  <rect x=\"14\" y=\"56\" width=\"162\" height=\"6\" rx=\"3\" fill=\"#fff\" opacity=\"0.12\"/>\n  <rect x=\"14\" y=\"56\" width=\"120\" height=\"6\" rx=\"3\" fill=\"url(#pp)\"/>\n</g>\n<g transform=\"translate(246,120)\">\n  <rect x=\"0\" y=\"0\" width=\"114\" height=\"80\" rx=\"12\" fill=\"#fff\" opacity=\"0.05\" stroke=\"#eab308\" stroke-opacity=\"0.4\"/>\n  <circle cx=\"34\" cy=\"34\" r=\"20\" fill=\"url(#bl)\" opacity=\"0.25\"/>\n  <text x=\"20\" y=\"44\" font-size=\"26\">🏅</text>\n  <circle cx=\"72\" cy=\"26\" r=\"9\" fill=\"#eab308\" opacity=\"0.85\"/>\n  <circle cx=\"94\" cy=\"26\" r=\"9\" fill=\"#fff\" opacity=\"0.12\"/>\n  <circle cx=\"72\" cy=\"50\" r=\"9\" fill=\"#fff\" opacity=\"0.12\"/>\n  <circle cx=\"94\" cy=\"50\" r=\"9\" fill=\"#fff\" opacity=\"0.12\"/>\n</g>"),
    whatIs: "這是你的個人主頁，把你在 Agent School 的整段特工生涯收進同一頁。你訓練了哪些 Agent、課上到哪一關、考到哪幾張證照、靠市場賺了多少錢，全部一目了然，不用在各功能間切來切去。簡單說，它就是你的「特工檔案」，既是給自己看的進度表，也是未來向別人展示實力的成績單。",
    features: [{"icon":"🪪","text":"訓練師檔案頭卡：編號 SA26010001、孵化師認證徽章、加入日期，加上「我的 Agent 數、累積點數 350、排行榜第 8、本月收益」四項即時數據"},{"icon":"🤖","text":"我的 Agent 清單：小助理 Aria（服役中）、銷售小幫手 Max（訓練中），顯示等級、狀態與技能圖示，可一鍵繼續訓練或上架市場"},{"icon":"📖","text":"學習進度條：孵化期 Lv.1 已完成、成績 92 分，成長期 Lv.2 尚未開始，用進度條清楚標出你走到哪"},{"icon":"🏅","text":"證照牆：孵化師、技能師、訓練師、架構師、畢業大師五級，已取得的亮起打勾，未解鎖的變灰，可直接前往報考"},{"icon":"💰","text":"收益總覽：本月與累計市場收益一眼看清，並引導你上架 Agent 開始賺分潤"}],
    steps: [{"icon":"👀","title":"看自己的檔案","desc":"頭卡確認你的認證等級、點數、排名與本月收益"},{"icon":"🤖","title":"管理 Agent","desc":"在「我的 Agent」點繼續訓練升級，或把練好的上架市場"},{"icon":"🏅","title":"盯著證照牆","desc":"看下一張要解鎖哪張證照，點「前往報考」去考試"},{"icon":"💰","title":"邁向變現","desc":"從收益總覽進市場上架 Agent，開始累積分潤"}],
    voice: "這裡是你的個人主頁，也就是你的特工檔案。最上面這張頭卡，就是你的身分證，上面有你的訓練師編號、目前的孵化師認證徽章，還有加入的日期；旁邊四個數字很重要，分別是你訓練了幾隻 Agent、累積了多少點數、目前在排行榜第幾名，以及這個月在市場上賺到的收益。往下看，「我的 Agent」會列出你養成的每一隻，像小助理 Aria 和銷售小幫手 Max，標清楚等級、是服役中還是訓練中，你可以直接點繼續訓練讓牠升級，或是把練好的牠上架到市場。再下面是學習進度，讓你知道孵化期、成長期各上到哪一關、考了幾分。右邊那道證照牆很有意思，從孵化師一路到畢業大師共五級，拿到的會亮起打勾，沒解鎖的就變灰，點一下就能前往報考。最下面則是收益總覽，提醒你只要把 Agent 上架，就能開始賺分潤。整頁就是讓你一眼看清自己走到哪、下一步該往哪走。",
  },
  "/learning": {
    emoji: "📖",
    title: "學習中心",
    tagline: "從孵化到畢業，五階段把你的 Agent 練成精",
    svg: scene("<rect x=\"28\" y=\"150\" width=\"60\" height=\"46\" rx=\"10\" fill=\"#fff\" opacity=\"0.06\" stroke=\"#a855f7\" stroke-opacity=\"0.45\"/>\n<text x=\"44\" y=\"180\" font-size=\"22\">🥚</text>\n<rect x=\"100\" y=\"132\" width=\"60\" height=\"64\" rx=\"10\" fill=\"#fff\" opacity=\"0.06\" stroke=\"#6366f1\" stroke-opacity=\"0.45\"/>\n<text x=\"116\" y=\"170\" font-size=\"22\">🐣</text>\n<rect x=\"172\" y=\"112\" width=\"60\" height=\"84\" rx=\"10\" fill=\"#fff\" opacity=\"0.08\" stroke=\"#22d3ee\" stroke-opacity=\"0.5\"/>\n<text x=\"188\" y=\"156\" font-size=\"22\">🐦</text>\n<rect x=\"244\" y=\"92\" width=\"60\" height=\"104\" rx=\"10\" fill=\"#fff\" opacity=\"0.06\" stroke=\"#eab308\" stroke-opacity=\"0.45\"/>\n<text x=\"260\" y=\"140\" font-size=\"22\">🦅</text>\n<rect x=\"316\" y=\"68\" width=\"60\" height=\"128\" rx=\"10\" fill=\"url(#pp)\" opacity=\"0.85\"/>\n<text x=\"332\" y=\"120\" font-size=\"22\">🦁</text>\n<line x1=\"88\" y1=\"170\" x2=\"100\" y2=\"162\" stroke=\"#fff\" stroke-opacity=\"0.25\" stroke-width=\"2\"/>\n<line x1=\"160\" y1=\"160\" x2=\"172\" y2=\"150\" stroke=\"#fff\" stroke-opacity=\"0.25\" stroke-width=\"2\"/>\n<line x1=\"232\" y1=\"150\" x2=\"244\" y2=\"142\" stroke=\"#fff\" stroke-opacity=\"0.25\" stroke-width=\"2\"/>\n<line x1=\"304\" y1=\"140\" x2=\"316\" y2=\"130\" stroke=\"#fff\" stroke-opacity=\"0.25\" stroke-width=\"2\"/>\n<rect x=\"36\" y=\"30\" width=\"120\" height=\"28\" rx=\"8\" fill=\"url(#bl)\" opacity=\"0.85\"/>\n<rect x=\"48\" y=\"40\" width=\"64\" height=\"6\" rx=\"3\" fill=\"#fff\" opacity=\"0.9\"/>\n<circle cx=\"138\" cy=\"44\" r=\"6\" fill=\"#22c55e\"/>\n<rect x=\"316\" y=\"40\" width=\"58\" height=\"20\" rx=\"10\" fill=\"#fff\" opacity=\"0.07\" stroke=\"#22c55e\" stroke-opacity=\"0.5\"/>\n<text x=\"324\" y=\"55\" font-size=\"13\" fill=\"#22c55e\">92分</text>"),
    whatIs: "學習中心是 Agent School 的「教室」，把你從零到變現的整段路一次鋪好。它解決一個痛點：AI Agent 名詞太多、不知從何學起。這裡用孵化、成長、訓練、進化、畢業五個階段幫你排好順序，每階段該懂哪些概念、上哪幾堂直播課、考哪些測驗，全都一目了然，照著走就不會迷路。",
    features: [{"icon":"🥚","text":"新手村概念圖鑑：Lv.1 到 Lv.5 五階段，點任一階展開該級的核心概念、進階心法、工具與商業概念卡片"},{"icon":"📚","text":"課程總覽：四位講師陣容 + 五堂真人直播課，含價格、直播時程、免費試聽/回放與單元清單，可一鍵報名"},{"icon":"🎒","text":"我的課程：追蹤已報名課程的「已完成／進行中」狀態與成績，完成的可看回放、進行中的直接進課"},{"icon":"📝","text":"測驗與成績：課後小測、等級認證、架構師認證，標明題數、及格分、限時，可作答的能立即開始"},{"icon":"🏅","text":"成績一覽：完成的測驗顯示得分，通過認證可取得官方等級與業界認可資格"}],
    steps: [{"icon":"🥚","title":"先逛新手村","desc":"點五階段的等級卡，展開概念圖鑑了解每級要學什麼"},{"icon":"📚","title":"挑課報名","desc":"切到課程總覽，看講師與時程，按「立即報名」卡位直播課"},{"icon":"🎒","title":"進課學習","desc":"在我的課程進入進行中的課，或回放已完成的內容"},{"icon":"📝","title":"考試認證","desc":"到測驗與成績，把可作答的測驗考過，累積成績與證書"}],
    voice: "歡迎來到學習中心，這裡是 Agent School 的教室，陪你從孵化一路練到畢業。最上面有四個分頁，我們一個一個看。第一個是新手村，這是一張完整的概念圖鑑，從孵化、成長、訓練、進化到畢業，總共五個階段，點任何一個等級卡，就會展開那一級該懂的所有概念，像是核心概念、進階心法、工具平台還有商業概念，每張卡都能點，會幫你加進學習清單。第二個分頁是課程總覽，這裡有四位真人講師的介紹，還有五堂直播課，每堂都標清楚價格、上課時間、免費試聽和單元內容，看中哪堂就按立即報名卡位。第三個是我的課程，可以看到你報名的課程是進行中還是已完成，完成的能看回放，進行中的直接進去上。最後一個是測驗與成績，從課後小測到架構師認證都有，標明題數、及格分數跟限時，可以作答的就按開始作答。照這個順序走，學、練、考一次到位。",
  },
  "/cert": {
    emoji: "🏅",
    title: "證照中心",
    tagline: "五級業界認證，永久上鏈、線上模擬考、電子證書對外可驗真",
    svg: scene("<rect x=\"40\" y=\"170\" width=\"40\" height=\"34\" rx=\"6\" fill=\"#fff\" opacity=\"0.06\" stroke=\"#a855f7\" stroke-opacity=\"0.4\"/>\n    <rect x=\"92\" y=\"156\" width=\"40\" height=\"48\" rx=\"6\" fill=\"#fff\" opacity=\"0.06\" stroke=\"#22d3ee\" stroke-opacity=\"0.4\"/>\n    <rect x=\"144\" y=\"138\" width=\"40\" height=\"66\" rx=\"6\" fill=\"url(#pp)\" opacity=\"0.9\"/>\n    <text x=\"150\" y=\"180\" font-size=\"13\" fill=\"#fff\" font-weight=\"bold\">Lv5</text>\n    <circle cx=\"280\" cy=\"78\" r=\"34\" fill=\"url(#pp)\"/>\n    <circle cx=\"280\" cy=\"78\" r=\"34\" fill=\"none\" stroke=\"#fff\" stroke-opacity=\"0.5\" stroke-width=\"2\"/>\n    <circle cx=\"280\" cy=\"78\" r=\"22\" fill=\"none\" stroke=\"#fff\" stroke-opacity=\"0.35\" stroke-width=\"1.5\"/>\n    <text x=\"280\" y=\"88\" font-size=\"26\" text-anchor=\"middle\">🏅</text>\n    <path d=\"M268 108 L262 150 L280 138 L298 150 L292 108 Z\" fill=\"url(#bl)\" opacity=\"0.85\"/>\n    <rect x=\"40\" y=\"44\" width=\"150\" height=\"14\" rx=\"7\" fill=\"#fff\" opacity=\"0.08\"/>\n    <rect x=\"40\" y=\"44\" width=\"44\" height=\"14\" rx=\"7\" fill=\"url(#pp)\"/>\n    <circle cx=\"51\" cy=\"51\" r=\"5\" fill=\"#fff\"/>\n    <circle cx=\"84\" cy=\"51\" r=\"4\" fill=\"#22d3ee\"/>\n    <circle cx=\"117\" cy=\"51\" r=\"4\" fill=\"#fff\" opacity=\"0.25\"/>\n    <circle cx=\"150\" cy=\"51\" r=\"4\" fill=\"#fff\" opacity=\"0.25\"/>\n    <circle cx=\"183\" cy=\"51\" r=\"4\" fill=\"#fff\" opacity=\"0.25\"/>\n    <rect x=\"320\" y=\"120\" width=\"58\" height=\"74\" rx=\"8\" fill=\"#fff\" opacity=\"0.07\" stroke=\"#22c55e\" stroke-opacity=\"0.4\"/>\n    <rect x=\"330\" y=\"132\" width=\"38\" height=\"5\" rx=\"2.5\" fill=\"#fff\" opacity=\"0.5\"/>\n    <rect x=\"330\" y=\"144\" width=\"30\" height=\"5\" rx=\"2.5\" fill=\"#fff\" opacity=\"0.3\"/>\n    <text x=\"338\" y=\"180\" font-size=\"20\">📝</text>"),
    whatIs: "證照中心是 Agent School 幫你把學習成果「變成一張對外能拿出手的證明」的地方。從 Lv.1 孵化師到 Lv.5 畢業大師，五級認證像打怪升級一樣一關關解鎖。點開每張證照，都清楚寫明報考資格、涵蓋技能、有效期和考費，可報考的證照能直接線上模擬考，及格後核發電子證書、寄到信箱、還能到成果展示公開分享。簡單說，它讓你的能力不只是嘴上講，而是業界認可、可驗真的硬實力。",
    features: [{"icon":"🪜","text":"五級認證地圖：孵化師→技能師→訓練師→架構師→畢業大師，逐級解鎖"},{"icon":"📊","text":"我的認證進度條，一眼看出已取得、可報考、未解鎖各是哪幾張"},{"icon":"📋","text":"每張證照攤開報考資格、涵蓋技能、有效期與考費（免費應考或單次費用）"},{"icon":"📝","text":"線上模擬考試：單選題、及格 80 分，繳卷後立刻算分顯示結果"},{"icon":"⬇","text":"通過後核發電子證書，可下載、寄信箱、到成果展示公開分享"}],
    steps: [{"icon":"🗺️","title":"看進度挑證照","desc":"先看上方進度條，從五張卡片裡點一張想考的證照"},{"icon":"📋","title":"確認資格與技能","desc":"在詳情區看清楚報考資格、涵蓋技能與考費"},{"icon":"📝","title":"開始考試作答","desc":"可報考的證照按「開始考試」，逐題單選作答後繳交"},{"icon":"🏅","title":"看分數領證書","desc":"達 80 分即通過，下載電子證書並公開分享"}],
    voice: "歡迎來到證照中心，這裡是把你的學習成果變成一張對外證明的地方。最上面是你的認證進度，一條進度條加五個徽章，清楚標出哪幾張已經取得、哪些可以報考、哪些還鎖著。我們總共有五級認證，從 Lv.1 孵化師、技能師、訓練師、架構師，一路到最高的 Lv.5 畢業大師，像打怪升級一樣一關一關解鎖。點選任何一張證照，下方就會攤開它的報考資格、認證涵蓋哪些技能，還有有效期跟考費，有些含在課程裡免費應考，有些則要單次費用。如果這張是可以報考的，按下開始考試，就會進入線上模擬考，全部是單選題，及格分數是八十分，作答完繳交，馬上幫你算分。只要通過，系統就核發電子證書，可以下載、寄到你的信箱，還能到成果展示公開分享給客戶看，讓你的實力不只是嘴上講，而是業界認可、可以驗真的真本事。",
  },
  "/training": {
    emoji: "🎓",
    title: "Agent 訓練所",
    tagline: "填資料、選技能，帶走一隻身懷絕技的 AI 特工",
    svg: scene("<rect x=\"150\" y=\"34\" width=\"120\" height=\"22\" rx=\"11\" fill=\"url(#pp)\" opacity=\"0.9\"/><circle cx=\"173\" cy=\"45\" r=\"6\" fill=\"#fff\" opacity=\"0.9\"/><circle cx=\"200\" cy=\"45\" r=\"6\" fill=\"#22d3ee\"/><circle cx=\"227\" cy=\"45\" r=\"6\" fill=\"#fff\" opacity=\"0.35\"/><rect x=\"170\" y=\"80\" width=\"60\" height=\"74\" rx=\"14\" fill=\"#fff\" opacity=\"0.07\" stroke=\"#a855f7\" stroke-opacity=\"0.5\"/><circle cx=\"200\" cy=\"104\" r=\"17\" fill=\"url(#bl)\"/><circle cx=\"194\" cy=\"101\" r=\"3\" fill=\"#0d0820\"/><circle cx=\"206\" cy=\"101\" r=\"3\" fill=\"#0d0820\"/><rect x=\"196\" y=\"109\" width=\"8\" height=\"3\" rx=\"1.5\" fill=\"#0d0820\"/><line x1=\"200\" y1=\"80\" x2=\"200\" y2=\"71\" stroke=\"#22d3ee\" stroke-width=\"2\"/><circle cx=\"200\" cy=\"68\" r=\"4\" fill=\"#22d3ee\"/><rect x=\"182\" y=\"126\" width=\"36\" height=\"6\" rx=\"3\" fill=\"#fff\" opacity=\"0.55\"/><rect x=\"187\" y=\"138\" width=\"26\" height=\"5\" rx=\"2.5\" fill=\"#fff\" opacity=\"0.3\"/><g><rect x=\"40\" y=\"76\" width=\"46\" height=\"34\" rx=\"9\" fill=\"#fff\" opacity=\"0.06\" stroke=\"#a855f7\" stroke-opacity=\"0.4\"/><text x=\"52\" y=\"99\" font-size=\"17\">🔍</text><rect x=\"40\" y=\"120\" width=\"46\" height=\"34\" rx=\"9\" fill=\"#fff\" opacity=\"0.06\" stroke=\"#22d3ee\" stroke-opacity=\"0.4\"/><text x=\"52\" y=\"143\" font-size=\"17\">📚</text></g><g><rect x=\"314\" y=\"76\" width=\"46\" height=\"34\" rx=\"9\" fill=\"#fff\" opacity=\"0.06\" stroke=\"#eab308\" stroke-opacity=\"0.4\"/><text x=\"326\" y=\"99\" font-size=\"17\">📧</text><rect x=\"314\" y=\"120\" width=\"46\" height=\"34\" rx=\"9\" fill=\"#fff\" opacity=\"0.06\" stroke=\"#22c55e\" stroke-opacity=\"0.4\"/><text x=\"326\" y=\"143\" font-size=\"17\">🧠</text></g><line x1=\"86\" y1=\"93\" x2=\"168\" y2=\"100\" stroke=\"#a855f7\" stroke-width=\"1.5\" stroke-opacity=\"0.5\" stroke-dasharray=\"3 3\"/><line x1=\"86\" y1=\"137\" x2=\"168\" y2=\"112\" stroke=\"#22d3ee\" stroke-width=\"1.5\" stroke-opacity=\"0.5\" stroke-dasharray=\"3 3\"/><line x1=\"232\" y1=\"100\" x2=\"314\" y2=\"93\" stroke=\"#eab308\" stroke-width=\"1.5\" stroke-opacity=\"0.5\" stroke-dasharray=\"3 3\"/><line x1=\"232\" y1=\"112\" x2=\"314\" y2=\"137\" stroke=\"#22c55e\" stroke-width=\"1.5\" stroke-opacity=\"0.5\" stroke-dasharray=\"3 3\"/><rect x=\"118\" y=\"176\" width=\"164\" height=\"30\" rx=\"8\" fill=\"url(#pp)\" opacity=\"0.85\"/><text x=\"200\" y=\"196\" font-size=\"13\" fill=\"#fff\" text-anchor=\"middle\" font-family=\"sans-serif\" font-weight=\"bold\">System Prompt ✅</text>"),
    whatIs: "這頁是 Agent School 的核心工坊，幫你把腦中模糊的「我想要一隻能做某件事的 AI」變成真正可用的設定檔。你不用會寫程式，只要填名字、講清楚用途、選個性，再勾選想要的技能，系統就會自動產生一段可以直接貼進 Claude、ChatGPT 或 Dify 的 System Prompt，還畫出這隻 Agent 的工作流程圖。不論是從零孵化新 Agent，還是把現有 Agent 送來升級技能，都在這裡一站完成。",
    features: [{"icon":"✨","text":"兩種模式：孵化全新 Agent，或送訓現有 Agent（可貼上舊 Prompt 在原基礎升級）"},{"icon":"📝","text":"三步驟精靈：填資料（名字、用途、個性）→ 選技能 → 確認生成，上方進度條清楚標示"},{"icon":"🎭","text":"個性風格一鍵套用：親切專業、幽默風趣、嚴謹精準、簡潔高效、溫暖陪伴，也可自行描述"},{"icon":"⚡","text":"分類技能包任選：資訊取得、溝通、生產力、創意、開發、記憶、商業、自動化八大類，熱門技能有標記"},{"icon":"🤖","text":"一鍵生成 System Prompt 與技能工作流圖，可複製、下載 JSON、匯出 Make.com/n8n，或去考認證、上架技能市場"}],
    steps: [{"icon":"📋","title":"填寫 Agent 資料","desc":"取個名字、寫清楚用途，再選一種個性風格，名字和用途填完才能進下一步"},{"icon":"⚡","title":"勾選技能包","desc":"從八大分類裡點選要安裝的技能，右上角即時顯示已選幾個，至少選一個"},{"icon":"🚀","title":"確認並開始訓練","desc":"檢視訓練摘要無誤後按開始訓練，系統生成 System Prompt 與技能工作流"},{"icon":"📥","title":"帶走成果","desc":"複製 Prompt、下載配置 JSON，或直接去考認證、上架技能市場賺錢"}],
    voice: "歡迎來到 Agent 訓練所，這裡是把你的想法變成一隻真正能幹活的 AI 特工的地方。整個流程分成三步，上方的進度條會告訴你走到哪。第一步，先幫你的 Agent 取個名字，比方說小助理 Aria，接著寫清楚它要幫你做什麼，再挑一種個性風格，有親切專業、幽默風趣、嚴謹精準這幾種可以一鍵套用，當然也能自己描述。名字和用途都填好，才會解鎖下一步。第二步是選技能包，這裡把技能分成資訊取得、溝通工具、生產力、創意、開發、記憶系統、商業工具、自動化八大類，像網路搜尋、知識庫、LINE 推播、長期記憶都在裡面，熱門的會特別標出來，右上角會即時顯示你選了幾個。第三步先看訓練摘要確認沒問題，按下開始訓練，系統就會生成一段 System Prompt，還畫出從輸入、經過你的 Agent、再串接各個技能到產出的工作流程圖。這段 Prompt 可以直接複製貼到 Claude 或 ChatGPT，也能下載成設定檔、匯出成 Make 或 n8n 藍圖，甚至直接去考認證或上架技能市場賺錢。一隻訓練完，還能再訓練下一隻。",
  },
  "/market": {
    emoji: "🛒",
    title: "Agent 市場",
    tagline: "買租別人練好的 Agent，上架自己的賺 70% 分潤",
    svg: scene("<rect x=\"150\" y=\"40\" width=\"210\" height=\"30\" rx=\"8\" fill=\"url(#pp)\" opacity=\"0.9\"/>\n<rect x=\"160\" y=\"49\" width=\"84\" height=\"6\" rx=\"3\" fill=\"#fff\" opacity=\"0.9\"/>\n<rect x=\"160\" y=\"60\" width=\"130\" height=\"5\" rx=\"2.5\" fill=\"#fff\" opacity=\"0.5\"/>\n<text x=\"316\" y=\"64\" font-size=\"22\">🛒</text>\n<g>\n  <rect x=\"40\" y=\"90\" width=\"150\" height=\"58\" rx=\"12\" fill=\"#fff\" opacity=\"0.06\" stroke=\"#a855f7\" stroke-opacity=\"0.45\"/>\n  <rect x=\"52\" y=\"102\" width=\"32\" height=\"32\" rx=\"9\" fill=\"url(#pp)\"/>\n  <text x=\"58\" y=\"125\" font-size=\"18\">🤖</text>\n  <rect x=\"94\" y=\"104\" width=\"78\" height=\"7\" rx=\"3.5\" fill=\"#fff\" opacity=\"0.85\"/>\n  <rect x=\"94\" y=\"116\" width=\"58\" height=\"5\" rx=\"2.5\" fill=\"#fff\" opacity=\"0.45\"/>\n  <rect x=\"94\" y=\"128\" width=\"40\" height=\"9\" rx=\"4.5\" fill=\"#22c55e\" opacity=\"0.85\"/>\n</g>\n<g>\n  <rect x=\"210\" y=\"90\" width=\"150\" height=\"58\" rx=\"12\" fill=\"#fff\" opacity=\"0.06\" stroke=\"#22d3ee\" stroke-opacity=\"0.45\"/>\n  <rect x=\"222\" y=\"102\" width=\"32\" height=\"32\" rx=\"9\" fill=\"url(#bl)\"/>\n  <text x=\"228\" y=\"125\" font-size=\"18\">💼</text>\n  <rect x=\"264\" y=\"104\" width=\"78\" height=\"7\" rx=\"3.5\" fill=\"#fff\" opacity=\"0.85\"/>\n  <rect x=\"264\" y=\"116\" width=\"58\" height=\"5\" rx=\"2.5\" fill=\"#fff\" opacity=\"0.45\"/>\n  <rect x=\"264\" y=\"128\" width=\"40\" height=\"9\" rx=\"4.5\" fill=\"#eab308\" opacity=\"0.85\"/>\n</g>\n<g transform=\"translate(40,166)\">\n  <rect x=\"0\" y=\"0\" width=\"78\" height=\"22\" rx=\"11\" fill=\"url(#pp)\" opacity=\"0.9\"/>\n  <text x=\"12\" y=\"16\" font-size=\"11\" fill=\"#fff\" font-family=\"sans-serif\">月租</text>\n  <rect x=\"84\" y=\"0\" width=\"78\" height=\"22\" rx=\"11\" fill=\"#fff\" opacity=\"0.08\" stroke=\"#fff\" stroke-opacity=\"0.18\"/>\n  <text x=\"98\" y=\"16\" font-size=\"11\" fill=\"#fff\" font-family=\"sans-serif\" opacity=\"0.6\">買斷</text>\n</g>\n<g transform=\"translate(300,168)\">\n  <circle cx=\"20\" cy=\"18\" r=\"22\" fill=\"#22c55e\" opacity=\"0.18\"/>\n  <text x=\"6\" y=\"28\" font-size=\"24\">💰</text>\n  <text x=\"40\" y=\"14\" font-size=\"11\" fill=\"#22c55e\" font-family=\"sans-serif\" font-weight=\"bold\">70%</text>\n  <text x=\"40\" y=\"28\" font-size=\"9\" fill=\"#fff\" font-family=\"sans-serif\" opacity=\"0.5\">分潤</text>\n</g>"),
    whatIs: "這裡是學員之間互相買賣 Agent 的交易市集。你不一定要從零訓練一隻 Agent，可以直接租用或買斷別人已經調教成熟、實際服役過的 Agent，馬上加進自己的工作台用。反過來，你自己練好的 Agent 也能上架販售，每筆交易你拿七成分潤、學校抽三成，等於把學習成果變成被動收入。一個地方同時解決「我需要好用的 Agent」和「我想靠 Agent 賺錢」兩件事。",
    features: [{"icon":"🔄","text":"月租／買斷雙模式切換，同一隻 Agent 看月費或一次買斷價"},{"icon":"🏷️","text":"分類標籤篩選（客服、銷售、內容創作、資料整理、企業知識庫、個人助理）快速找到要的 Agent"},{"icon":"🤖","text":"每張 Agent 卡列出技能標籤、星級評分與評論數、使用人數、訓練者與認證等級"},{"icon":"📊","text":"市場數據總覽：上架 247 隻、本月成交 NT$1.2M、平均評分 4.8 星、認證師上架率 78%"},{"icon":"💰","text":"上架自己的 Agent，每筆交易拿 70% 分潤（學校抽 30%），頂尖 Agent 月收 3 到 8 萬"}],
    steps: [{"icon":"🔄","title":"選模式","desc":"先決定要月租還是買斷，價格會跟著切換"},{"icon":"🏷️","title":"挑分類","desc":"用上方分類標籤縮小範圍，找符合需求的 Agent"},{"icon":"🛒","title":"租或買","desc":"看技能、評分、使用人數，按立即租用或立即購買加進工作台"},{"icon":"💰","title":"上架賺錢","desc":"點上架我的 Agent 去訓練，發布後每筆交易拿 70%"}],
    voice: "歡迎來到 Agent 市場，這裡是學員之間互相買賣 Agent 的交易市集。你不用每隻都自己從頭訓練，可以直接租用或買斷別人已經調教成熟的 Agent，馬上加進你的工作台。最上方四張卡片是整個市場的脈動：目前上架了兩百四十七隻 Agent，本月成交金額一百二十萬，平均評分四點八顆星，而且持有認證的訓練師上架率高達七成八。卡片下面有個切換鈕，左邊是月租模式，右邊是買斷模式，價格會跟著變，旁邊還有一排分類標籤幫你快速篩選。每一張 Agent 卡都寫得很清楚，包含它會哪些技能、幾顆星、多少人正在使用，還有是哪位訓練師做的、拿到什麼等級的認證。看上眼就按立即租用或立即購買。最後別忘了，你自己練好的 Agent 也能上架販售，每筆交易你拿七成分潤、學校抽三成，頂尖的 Agent 一個月能賺三到八萬，把學習直接變成收入。",
  },
  "/tasks": {
    emoji: "💼",
    title: "任務中心",
    tagline: "真實接案任務板，靠你的 Agent 技能賺取報酬",
    svg: scene("<rect x=\"44\" y=\"40\" width=\"312\" height=\"30\" rx=\"8\" fill=\"url(#pp)\" opacity=\"0.9\"/><text x=\"58\" y=\"61\" font-size=\"16\">💼</text><rect x=\"84\" y=\"48\" width=\"80\" height=\"6\" rx=\"3\" fill=\"#fff\" opacity=\"0.9\"/><rect x=\"84\" y=\"60\" width=\"130\" height=\"5\" rx=\"2.5\" fill=\"#fff\" opacity=\"0.45\"/><g><rect x=\"44\" y=\"84\" width=\"150\" height=\"60\" rx=\"10\" fill=\"#fff\" opacity=\"0.06\" stroke=\"#a855f7\" stroke-opacity=\"0.4\"/><rect x=\"58\" y=\"96\" width=\"74\" height=\"7\" rx=\"3.5\" fill=\"#fff\" opacity=\"0.85\"/><rect x=\"58\" y=\"111\" width=\"40\" height=\"13\" rx=\"6.5\" fill=\"#22c55e\" opacity=\"0.18\" stroke=\"#22c55e\" stroke-opacity=\"0.4\"/><rect x=\"64\" y=\"115\" width=\"28\" height=\"5\" rx=\"2.5\" fill=\"#22c55e\"/><rect x=\"58\" y=\"131\" width=\"34\" height=\"8\" rx=\"4\" fill=\"#fff\" opacity=\"0.1\"/><rect x=\"96\" y=\"131\" width=\"44\" height=\"8\" rx=\"4\" fill=\"#fff\" opacity=\"0.1\"/></g><g><rect x=\"206\" y=\"84\" width=\"150\" height=\"60\" rx=\"10\" fill=\"#fff\" opacity=\"0.06\" stroke=\"#22d3ee\" stroke-opacity=\"0.4\"/><rect x=\"220\" y=\"96\" width=\"68\" height=\"7\" rx=\"3.5\" fill=\"#fff\" opacity=\"0.85\"/><rect x=\"220\" y=\"111\" width=\"40\" height=\"13\" rx=\"6.5\" fill=\"#eab308\" opacity=\"0.18\" stroke=\"#eab308\" stroke-opacity=\"0.4\"/><rect x=\"226\" y=\"115\" width=\"28\" height=\"5\" rx=\"2.5\" fill=\"#eab308\"/><rect x=\"220\" y=\"131\" width=\"34\" height=\"8\" rx=\"4\" fill=\"#fff\" opacity=\"0.1\"/><rect x=\"258\" y=\"131\" width=\"44\" height=\"8\" rx=\"4\" fill=\"#fff\" opacity=\"0.1\"/></g><g transform=\"translate(44,160)\"><rect x=\"0\" y=\"0\" width=\"190\" height=\"40\" rx=\"10\" fill=\"#fff\" opacity=\"0.05\" stroke=\"#fff\" stroke-opacity=\"0.1\"/><text x=\"12\" y=\"27\" font-size=\"18\">💰</text><rect x=\"40\" y=\"13\" width=\"64\" height=\"8\" rx=\"4\" fill=\"#22c55e\" opacity=\"0.9\"/><rect x=\"40\" y=\"26\" width=\"40\" height=\"5\" rx=\"2.5\" fill=\"#fff\" opacity=\"0.4\"/></g><g transform=\"translate(252,160)\"><rect x=\"0\" y=\"0\" width=\"104\" height=\"40\" rx=\"12\" fill=\"url(#bl)\"/><rect x=\"22\" y=\"16\" width=\"60\" height=\"8\" rx=\"4\" fill=\"#fff\" opacity=\"0.95\"/></g>"),
    whatIs: "這裡是你把訓練成果變成收入的地方。市場上有人真的需要 Agent 來幫他做事，他們把需求發布成一張張任務卡，標明要什麼技能、給多少報酬、什麼時候要交。你只要看看哪一張任務剛好對得上你練好的本事，按下申請接案就能投出去。這頁幫你解決「學了一身技能不知道去哪用」的問題，把學習和賺錢直接接起來。",
    features: [{"icon":"📊","text":"頂部四張統計卡：可接任務 4 件、審核中 1 件、進行中 1 件、累計收益 NT$8,000"},{"icon":"🚦","text":"每張任務標難度，用顏色分級：綠色初級、黃色中級、紅色高級"},{"icon":"🧩","text":"任務卡列出需要的技能標籤，例如客戶管理、知識庫 RAG、LINE 推播，一眼看出接不接得起"},{"icon":"💰","text":"右側清楚標示報酬金額、可得積分與截止日期，從 NT$8,000 到 NT$45,000 不等"},{"icon":"✅","text":"按「申請接案」一鍵投件，送出後系統會通知你接案結果"}],
    steps: [{"icon":"📊","title":"先看總覽","desc":"頂部四張卡掌握目前可接幾件、累計賺了多少"},{"icon":"🔍","title":"挑對任務","desc":"看難度顏色和技能標籤，找你 Agent 接得起的那張"},{"icon":"💵","title":"比報酬期限","desc":"看右側報酬、積分和截止日，評估值不值得做"},{"icon":"✅","title":"申請接案","desc":"按下申請接案投件，等待系統通知接案結果"}],
    voice: "歡迎來到任務中心，這裡是你把訓練好的 Agent 技能變現的地方。先看最上面那四張卡片，它告訴你現在有幾件任務可以接、幾件正在審核、幾件進行中，還有你累計賺到的收益。再往下就是最新發布的任務清單，每一張卡片都是一個真實的接案需求。卡片左邊有任務名稱跟一個難度標籤，綠色是初級、黃色是中級、紅色是高級，難度越高報酬越豐厚。下面那些小圓標就是這個任務需要的技能，像是客戶管理、知識庫、或是 LINE 推播，你可以對照自己練好的本事，看看接不接得起來。卡片右邊寫得很清楚，給你多少新台幣、能拿多少積分、什麼時候截止。看到喜歡又合適的任務，直接按下申請接案，送出之後系統就會通知你接案的結果。挑你最有把握的那張，從第一筆收入開始吧。",
  },
  "/skills": {
    emoji: "⚡",
    title: "技能市場",
    tagline: "為你的 Agent 挑技能、按安裝，即插即用上戰場",
    svg: scene("<rect x=\"40\" y=\"34\" width=\"150\" height=\"26\" rx=\"8\" fill=\"url(#pp)\" opacity=\"0.9\"/><text x=\"52\" y=\"52\" font-size=\"14\" fill=\"#fff\" opacity=\"0.95\">⚡ 技能市場</text><text x=\"338\" y=\"56\" font-size=\"22\">🛒</text><g><rect x=\"40\" y=\"74\" width=\"100\" height=\"42\" rx=\"10\" fill=\"#fff\" opacity=\"0.06\" stroke=\"#a855f7\" stroke-opacity=\"0.45\"/><text x=\"58\" y=\"102\" font-size=\"18\">🧩</text><rect x=\"86\" y=\"84\" width=\"42\" height=\"6\" rx=\"3\" fill=\"#fff\" opacity=\"0.55\"/><rect x=\"86\" y=\"98\" width=\"30\" height=\"5\" rx=\"2.5\" fill=\"#fff\" opacity=\"0.35\"/></g><g><rect x=\"150\" y=\"74\" width=\"100\" height=\"42\" rx=\"10\" fill=\"#fff\" opacity=\"0.06\" stroke=\"#22d3ee\" stroke-opacity=\"0.45\"/><text x=\"168\" y=\"102\" font-size=\"18\">🗂️</text><rect x=\"196\" y=\"84\" width=\"42\" height=\"6\" rx=\"3\" fill=\"#fff\" opacity=\"0.55\"/><rect x=\"196\" y=\"98\" width=\"30\" height=\"5\" rx=\"2.5\" fill=\"#fff\" opacity=\"0.35\"/></g><g><rect x=\"260\" y=\"74\" width=\"100\" height=\"42\" rx=\"10\" fill=\"#fff\" opacity=\"0.06\" stroke=\"#eab308\" stroke-opacity=\"0.5\"/><text x=\"278\" y=\"102\" font-size=\"18\">🔥</text><rect x=\"306\" y=\"84\" width=\"42\" height=\"6\" rx=\"3\" fill=\"#fff\" opacity=\"0.55\"/><rect x=\"306\" y=\"98\" width=\"30\" height=\"5\" rx=\"2.5\" fill=\"#fff\" opacity=\"0.35\"/></g><g><rect x=\"40\" y=\"132\" width=\"155\" height=\"60\" rx=\"12\" fill=\"#fff\" opacity=\"0.07\" stroke=\"#a855f7\" stroke-opacity=\"0.4\"/><circle cx=\"64\" cy=\"160\" r=\"14\" fill=\"url(#pp)\" opacity=\"0.9\"/><text x=\"56\" y=\"166\" font-size=\"14\">🔍</text><rect x=\"86\" y=\"148\" width=\"64\" height=\"7\" rx=\"3.5\" fill=\"#fff\" opacity=\"0.7\"/><rect x=\"86\" y=\"162\" width=\"92\" height=\"5\" rx=\"2.5\" fill=\"#fff\" opacity=\"0.35\"/><rect x=\"86\" y=\"173\" width=\"40\" height=\"13\" rx=\"6.5\" fill=\"#a855f7\" opacity=\"0.3\" stroke=\"#a855f7\" stroke-opacity=\"0.5\"/><text x=\"94\" y=\"183\" font-size=\"8\" fill=\"#d8b4fe\">安裝</text></g><g><rect x=\"205\" y=\"132\" width=\"155\" height=\"60\" rx=\"12\" fill=\"#fff\" opacity=\"0.07\" stroke=\"#22d3ee\" stroke-opacity=\"0.4\"/><circle cx=\"229\" cy=\"160\" r=\"14\" fill=\"url(#bl)\" opacity=\"0.9\"/><text x=\"221\" y=\"166\" font-size=\"14\">🧠</text><rect x=\"251\" y=\"148\" width=\"58\" height=\"7\" rx=\"3.5\" fill=\"#fff\" opacity=\"0.7\"/><rect x=\"316\" y=\"146\" width=\"34\" height=\"12\" rx=\"6\" fill=\"#eab308\" opacity=\"0.25\" stroke=\"#eab308\" stroke-opacity=\"0.5\"/><text x=\"321\" y=\"155\" font-size=\"7.5\" fill=\"#fde047\">熱門</text><rect x=\"251\" y=\"162\" width=\"92\" height=\"5\" rx=\"2.5\" fill=\"#fff\" opacity=\"0.35\"/><rect x=\"251\" y=\"173\" width=\"48\" height=\"13\" rx=\"6.5\" fill=\"#22c55e\" opacity=\"0.25\" stroke=\"#22c55e\" stroke-opacity=\"0.5\"/><text x=\"258\" y=\"183\" font-size=\"8\" fill=\"#86efac\">已安裝 ✓</text></g>"),
    whatIs: "技能市場就像 Agent 的應用商店。你訓練出來的 Agent 一開始只是個空殼，要它會做事，就得替它裝上對應的本領。這一頁把十六個現成的技能模組整整齊齊擺出來，從網路搜尋、寄信、LINE 推播，到長期記憶、金流串接、排程自動化都有。每個都是即插即用，看中哪個，把滑鼠移上去按下安裝就生效，不用寫一行程式，幾秒鐘就幫你的 Agent 補上一身武功。",
    features: [{"icon":"🧩","text":"16 個即插即用技能模組，滑到卡片上按一下安裝就生效，免寫程式"},{"icon":"🗂️","text":"依用途分成資訊取得、溝通工具、生產力、創意工具、開發工具、記憶系統、商業工具、自動化共 8 大分類，每類旁標數量"},{"icon":"🔥","text":"熱門技能（網路搜尋、知識庫 RAG、LINE 推播、試算表、程式執行、長期記憶、客戶管理）標上黃色「熱門」標籤，新手照著裝不踩雷"},{"icon":"📊","text":"頂部統計列即時顯示可安裝技能數、分類數、熱門技能數三項數字"},{"icon":"⚡","text":"涵蓋搜尋、Email、行事曆、試算表、圖像生成、語音 TTS、程式執行、瀏覽器操控、金流、Webhook 等真實工作場景"}],
    steps: [{"icon":"👀","title":"看統計列","desc":"先掃一眼頂部三張卡，掌握有幾個技能、幾類、幾個熱門"},{"icon":"🗂️","title":"挑分類找技能","desc":"往下捲，依分類標題找到你的 Agent 需要的本領"},{"icon":"🖱️","title":"移上去看安裝鈕","desc":"滑鼠停在技能卡上，右側的「安裝」按鈕就會浮現"},{"icon":"✓","title":"按下安裝","desc":"點安裝，按鈕變成「已安裝」，技能就加進你的 Agent 工作台"}],
    voice: "歡迎來到技能市場，這裡就像是你 Agent 專屬的應用商店。你訓練出來的 Agent 一開始什麼都不會，要它能幹活，就得來這裡幫它裝技能。整頁總共有十六個現成的技能模組，全部都是即插即用，不用你寫任何程式。最上面這一排有三個數字，分別告訴你現在有幾個可安裝的技能、分成幾個分類、還有幾個是熱門技能。再往下，技能就依照用途排好了，有負責找資料的資訊取得、會寄信和發 LINE 的溝通工具，還有生產力、創意工具、開發工具、記憶系統、商業工具，以及自動化排程，每個分類旁邊都標了數量。想裝哪個技能，把滑鼠移到那張卡片上，右邊就會浮出一顆安裝按鈕，按下去它馬上變成已安裝，這個技能就加進你的 Agent 工作台了。標了黃色熱門兩個字的，是大家最常裝的，像是網路搜尋、知識庫、LINE 推播、長期記憶跟客戶管理，新手照著裝準沒錯。",
  },
  "/leaderboard": {
    emoji: "🏆",
    title: "訓練師排行榜",
    tagline: "依本月 Agent 市場收益排名，看頒獎台、追晉升差距",
    svg: scene("<rect x=\"40\" y=\"150\" width=\"90\" height=\"46\" rx=\"8\" fill=\"#fff\" opacity=\"0.06\" stroke=\"#6366f1\" stroke-opacity=\"0.5\"/><rect x=\"135\" y=\"110\" width=\"90\" height=\"86\" rx=\"8\" fill=\"url(#pp)\" opacity=\"0.85\"/><rect x=\"230\" y=\"166\" width=\"90\" height=\"30\" rx=\"8\" fill=\"#fff\" opacity=\"0.06\" stroke=\"#22d3ee\" stroke-opacity=\"0.5\"/><circle cx=\"85\" cy=\"130\" r=\"14\" fill=\"#fff\" opacity=\"0.12\" stroke=\"#c0c0c0\" stroke-opacity=\"0.6\"/><circle cx=\"180\" cy=\"86\" r=\"17\" fill=\"#fff\" opacity=\"0.14\" stroke=\"#eab308\" stroke-opacity=\"0.8\"/><circle cx=\"275\" cy=\"148\" r=\"13\" fill=\"#fff\" opacity=\"0.12\" stroke=\"#cd7f32\" stroke-opacity=\"0.7\"/><text x=\"76\" y=\"136\" font-size=\"16\">🥈</text><text x=\"170\" y=\"92\" font-size=\"20\">🥇</text><text x=\"266\" y=\"154\" font-size=\"15\">🥉</text><rect x=\"58\" y=\"168\" width=\"54\" height=\"6\" rx=\"3\" fill=\"#fff\" opacity=\"0.5\"/><rect x=\"148\" y=\"128\" width=\"64\" height=\"7\" rx=\"3.5\" fill=\"#fff\" opacity=\"0.85\"/><rect x=\"148\" y=\"142\" width=\"48\" height=\"6\" rx=\"3\" fill=\"#fff\" opacity=\"0.55\"/><rect x=\"244\" y=\"180\" width=\"50\" height=\"6\" rx=\"3\" fill=\"#fff\" opacity=\"0.5\"/><g transform=\"translate(168,52)\"><circle cx=\"12\" cy=\"12\" r=\"12\" fill=\"#eab308\" opacity=\"0.9\"/><path d=\"M12 5 l2 4.5 l5 .4 l-3.8 3.3 l1.2 4.9 l-4.4-2.6 l-4.4 2.6 l1.2-4.9 l-3.8-3.3 l5-.4 z\" fill=\"#fff\" opacity=\"0.95\"/></g><line x1=\"180\" y1=\"40\" x2=\"180\" y2=\"35\" stroke=\"#eab308\" stroke-width=\"2\" opacity=\"0.6\"/><rect x=\"338\" y=\"60\" width=\"46\" height=\"120\" rx=\"9\" fill=\"#fff\" opacity=\"0.05\" stroke=\"#22c55e\" stroke-opacity=\"0.4\"/><text x=\"349\" y=\"92\" font-size=\"15\">📈</text><rect x=\"346\" y=\"108\" width=\"30\" height=\"6\" rx=\"3\" fill=\"#22c55e\" opacity=\"0.7\"/><rect x=\"346\" y=\"122\" width=\"22\" height=\"6\" rx=\"3\" fill=\"#fff\" opacity=\"0.4\"/><rect x=\"346\" y=\"148\" width=\"30\" height=\"18\" rx=\"6\" fill=\"url(#bl)\" opacity=\"0.85\"/>"),
    whatIs: "這頁是 Agent School 的訓練師擂台。它把所有訓練師依「本月 Agent 在市場上賺到的收益」由高到低排名，讓你一眼看到誰最會做能賺錢的 Agent。對你來說，它不只是看熱鬧，而是把抽象的努力變成具體的名次和金額差距，告訴你「再追多少錢就能往上爬一名」，並直接給你下一步該做什麼，把競爭變成可執行的動力。",
    features: [{"icon":"🥇","text":"前三名頒獎台：金銀銅獎牌＋名字＋月收，台子高低對應名次"},{"icon":"📋","text":"完整排行榜：排名、訓練師、上架 Agent 數、本月收益、評分一字排開"},{"icon":"🏅","text":"榮譽徽章與證照鳥階：本月MVP、架構師之星、新星上升，搭配🦅🐦🐣🥚證照等級"},{"icon":"📍","text":"你的位置高亮：清楚標出「你」目前在第 8 名（綠色標記）"},{"icon":"📈","text":"我的晉升路徑：顯示現在排名、追上前一名要補多少收益、以及提升的行動按鈕"}],
    steps: [{"icon":"👀","title":"看頒獎台","desc":"先掃前三名，了解頂尖訓練師靠幾隻 Agent、賺多少站上去"},{"icon":"🔍","title":"找到自己","desc":"在完整榜單往下找綠色「你」那一列，看自己的名次與收益"},{"icon":"🎯","title":"算晉升差距","desc":"看底部晉升路徑，得知追上下一名還差多少 NT$"},{"icon":"🚀","title":"去訓練上架","desc":"點「訓練 Agent 上架」按鈕，做出能賺錢的 Agent 往上爬"}],
    voice: "歡迎來到訓練師排行榜，這裡是大家比拚實力的擂台。所有訓練師都依照這個月 Agent 在市場上賺到的收益來排名，每個月一號更新一次。最上面是冠亞季軍的頒獎台，金銀銅三面獎牌一字排開，台子越高名次越前面，你會看到他們各自帶了幾隻 Agent、月收多少。往下是完整榜單，從排名、訓練師名字、上架的 Agent 數量、本月收益到評分，全都列得清清楚楚，厲害的人還會掛上像本月MVP、架構師之星這類榮譽徽章，名字旁邊的小鳥圖示則代表證照等級，從老鷹一路到還沒孵化的蛋。別忘了找一找綠色標著你的那一列，那就是你現在的位置，目前在第八名。最後最實用的是底部的晉升路徑，它會告訴你追上前一名還差多少收益，只要按下訓練 Agent 上架，就能朝更高的名次前進。",
  },
  "/calendar": {
    emoji: "📅",
    title: "行事曆",
    tagline: "月曆一眼看完直播課、平台活動與任務截止日",
    svg: scene("<rect x=\"40\" y=\"40\" width=\"320\" height=\"150\" rx=\"14\" fill=\"#fff\" opacity=\"0.05\" stroke=\"#a855f7\" stroke-opacity=\"0.35\"/>\n<rect x=\"40\" y=\"40\" width=\"320\" height=\"34\" rx=\"14\" fill=\"url(#pp)\" opacity=\"0.85\"/>\n<rect x=\"56\" y=\"52\" width=\"92\" height=\"9\" rx=\"4.5\" fill=\"#fff\" opacity=\"0.95\"/>\n<circle cx=\"330\" cy=\"57\" r=\"9\" fill=\"#fff\" opacity=\"0.18\"/>\n<text x=\"324\" y=\"61\" font-size=\"11\" fill=\"#fff\">←</text>\n<g opacity=\"0.55\">\n<line x1=\"40\" y1=\"90\" x2=\"360\" y2=\"90\" stroke=\"#fff\" stroke-opacity=\"0.12\"/>\n<line x1=\"40\" y1=\"123\" x2=\"360\" y2=\"123\" stroke=\"#fff\" stroke-opacity=\"0.12\"/>\n<line x1=\"40\" y1=\"156\" x2=\"360\" y2=\"156\" stroke=\"#fff\" stroke-opacity=\"0.12\"/>\n<line x1=\"86\" y1=\"74\" x2=\"86\" y2=\"190\" stroke=\"#fff\" stroke-opacity=\"0.12\"/>\n<line x1=\"132\" y1=\"74\" x2=\"132\" y2=\"190\" stroke=\"#fff\" stroke-opacity=\"0.12\"/>\n<line x1=\"178\" y1=\"74\" x2=\"178\" y2=\"190\" stroke=\"#fff\" stroke-opacity=\"0.12\"/>\n<line x1=\"224\" y1=\"74\" x2=\"224\" y2=\"190\" stroke=\"#fff\" stroke-opacity=\"0.12\"/>\n<line x1=\"270\" y1=\"74\" x2=\"270\" y2=\"190\" stroke=\"#fff\" stroke-opacity=\"0.12\"/>\n<line x1=\"316\" y1=\"74\" x2=\"316\" y2=\"190\" stroke=\"#fff\" stroke-opacity=\"0.12\"/>\n</g>\n<rect x=\"138\" y=\"96\" width=\"34\" height=\"22\" rx=\"6\" fill=\"url(#pp)\" opacity=\"0.9\"/>\n<circle cx=\"155\" cy=\"113\" r=\"2\" fill=\"#fff\"/>\n<rect x=\"230\" y=\"129\" width=\"34\" height=\"22\" rx=\"6\" fill=\"url(#bl)\" opacity=\"0.9\"/>\n<circle cx=\"247\" cy=\"146\" r=\"2\" fill=\"#fff\"/>\n<rect x=\"92\" y=\"162\" width=\"34\" height=\"22\" rx=\"6\" fill=\"#ef4444\" opacity=\"0.45\" stroke=\"#ef4444\" stroke-opacity=\"0.6\"/>\n<circle cx=\"109\" cy=\"179\" r=\"2\" fill=\"#fca5a5\"/>\n<text x=\"296\" y=\"184\" font-size=\"26\">🗓️</text>"),
    whatIs: "行事曆把你在 Agent School 裡所有「跟時間有關」的事，全部收進同一張月曆。哪天有直播課要上、哪天有招生說明會或變現講座、哪個接案任務快截止了，過去散在各個頁面，現在一頁就看完。它幫你不漏掉任何一堂課、不錯過任何一個截止日，讓學習和接案的節奏都抓得準準的。",
    features: [{"icon":"🎨","text":"三色篩選標籤：課程直播（紫）、平台活動（藍）、任務截止（紅），一眼分清事件類型"},{"icon":"🗓️","text":"2026 年 7 月月曆視圖，有排程的日期亮起紫色光點，空檔一目了然"},{"icon":"📋","text":"近期排程清單，列出最近 12 筆事件的日期、時間、標題與類型，點一下看細節"},{"icon":"➕","text":"「+ 新增個人活動」按鈕，把自己的安排也加進這張行事曆"},{"icon":"◀","text":"左右箭頭切換月份，掌握不同月份的公開排程"}],
    steps: [{"icon":"🎨","title":"先認顏色","desc":"上方三個標籤代表三種事件，紫色課程、藍色活動、紅色截止"},{"icon":"🗓️","title":"看月曆找亮點","desc":"月曆上亮起、帶光點的日期就是有安排的日子"},{"icon":"📋","title":"往下看清單","desc":"近期排程列出每筆事件，點任一筆看日期時間與內容"},{"icon":"➕","title":"加自己的事","desc":"按右上角新增個人活動，把私人排程一起管理"}],
    voice: "歡迎來到行事曆，這一頁把你在 Agent School 裡所有跟時間有關的事，通通收進同一張月曆。最上面有三個彩色標籤，分別代表三種事件，紫色是課程直播，藍色是平台活動，像招生說明會或是教你用 Agent 多賺五萬的講座，紅色則是任務截止日，提醒你接的案子什麼時候要交。中間這張是二〇二六年七月的月曆，凡是有安排的日子，格子就會亮起來，還會冒出一個小紫點，哪天有事、哪天有空，一眼就分得出來，上面的左右箭頭可以切換月份。再往下捲，是近期排程清單，把最近的事件一筆一筆列出來，標好日期、時間、標題跟類型，點任何一筆就能看到細節。右上角還有一個新增個人活動的按鈕，讓你把自己的私人安排也加進來，學習跟接案的節奏，從此一手掌握。",
  },
  "/resources": {
    emoji: "🗂️",
    title: "資源中心",
    tagline: "Agent 套件、場景範本、擴充插件，即裝即用",
    svg: scene("<rect x=\"40\" y=\"40\" width=\"320\" height=\"20\" rx=\"6\" fill=\"#fff\" opacity=\"0.06\"/>\n<rect x=\"50\" y=\"46\" width=\"70\" height=\"8\" rx=\"4\" fill=\"url(#pp)\" opacity=\"0.9\"/>\n<rect x=\"130\" y=\"47\" width=\"44\" height=\"6\" rx=\"3\" fill=\"#fff\" opacity=\"0.4\"/>\n<rect x=\"184\" y=\"47\" width=\"44\" height=\"6\" rx=\"3\" fill=\"#fff\" opacity=\"0.4\"/>\n<g>\n<rect x=\"40\" y=\"76\" width=\"100\" height=\"64\" rx=\"10\" fill=\"#fff\" opacity=\"0.07\" stroke=\"#a855f7\" stroke-opacity=\"0.45\"/>\n<text x=\"52\" y=\"100\" font-size=\"18\">📦</text>\n<rect x=\"52\" y=\"110\" width=\"56\" height=\"6\" rx=\"3\" fill=\"#fff\" opacity=\"0.7\"/>\n<rect x=\"52\" y=\"121\" width=\"76\" height=\"5\" rx=\"2.5\" fill=\"#fff\" opacity=\"0.35\"/>\n<rect x=\"96\" y=\"86\" width=\"34\" height=\"13\" rx=\"6.5\" fill=\"#22c55e\" opacity=\"0.2\" stroke=\"#22c55e\" stroke-opacity=\"0.4\"/>\n</g>\n<g>\n<rect x=\"150\" y=\"76\" width=\"100\" height=\"64\" rx=\"10\" fill=\"#fff\" opacity=\"0.07\" stroke=\"#22d3ee\" stroke-opacity=\"0.45\"/>\n<text x=\"162\" y=\"100\" font-size=\"18\">📋</text>\n<rect x=\"162\" y=\"110\" width=\"56\" height=\"6\" rx=\"3\" fill=\"#fff\" opacity=\"0.7\"/>\n<rect x=\"162\" y=\"121\" width=\"72\" height=\"5\" rx=\"2.5\" fill=\"#fff\" opacity=\"0.35\"/>\n<rect x=\"206\" y=\"86\" width=\"34\" height=\"13\" rx=\"6.5\" fill=\"#eab308\" opacity=\"0.2\" stroke=\"#eab308\" stroke-opacity=\"0.4\"/>\n</g>\n<g>\n<rect x=\"260\" y=\"76\" width=\"100\" height=\"64\" rx=\"10\" fill=\"#fff\" opacity=\"0.07\" stroke=\"#ec4899\" stroke-opacity=\"0.45\"/>\n<text x=\"272\" y=\"100\" font-size=\"18\">🔌</text>\n<rect x=\"272\" y=\"110\" width=\"56\" height=\"6\" rx=\"3\" fill=\"#fff\" opacity=\"0.7\"/>\n<rect x=\"272\" y=\"121\" width=\"64\" height=\"5\" rx=\"2.5\" fill=\"#fff\" opacity=\"0.35\"/>\n</g>\n<rect x=\"40\" y=\"158\" width=\"150\" height=\"30\" rx=\"9\" fill=\"url(#pp)\" opacity=\"0.9\"/>\n<text x=\"58\" y=\"178\" font-size=\"13\">⬇️</text>\n<rect x=\"80\" y=\"170\" width=\"92\" height=\"7\" rx=\"3.5\" fill=\"#fff\" opacity=\"0.85\"/>\n<rect x=\"204\" y=\"158\" width=\"156\" height=\"30\" rx=\"9\" fill=\"#fff\" opacity=\"0.06\" stroke=\"#fff\" stroke-opacity=\"0.18\"/>\n<rect x=\"220\" y=\"170\" width=\"120\" height=\"7\" rx=\"3.5\" fill=\"#fff\" opacity=\"0.45\"/>\n<circle cx=\"332\" cy=\"64\" r=\"5\" fill=\"#22c55e\"/>"),
    whatIs: "這裡是 Agent School 的「應用商店」，把別人做好的 Agent 零件全攤在你面前。不用從零寫程式，你可以直接拿現成的應用套件、場景範本和瀏覽器擴充插件來組裝自己的 AI 特工。新手想快速做出第一個能跑的 Agent、老手想省下重複造輪子的時間，都能在這找到即裝即用的素材，標了「可試用」的還能先試過再決定要不要留下。",
    features: [{"icon":"📦","text":"應用套件：六款現成套件，像 RAG 知識庫、LINE Bot 部署包、Multi-Agent 協調器，附作者、版本與安裝數，按「安裝套件」加進工作台"},{"icon":"📋","text":"場景範本：六種現成工作流（新聞摘要推播、客服自動分流、社群內容產生等），按「使用範本」直接帶你到訓練場套用"},{"icon":"🔌","text":"擴充插件：三款 Chrome 外掛（Agent 監控、Prompt 測試、技能注入），滑過卡片即可一鍵安裝"},{"icon":"🏷️","text":"熱門與可試用標籤：熱門款一眼看到，標「可試用」的能先試過再決定要不要留下"},{"icon":"🧪","text":"資源瀏覽／我的試用雙分頁：在「我的試用」集中管理試用中的資源"}],
    steps: [{"icon":"🔍","title":"切到資源瀏覽","desc":"預設停在「資源瀏覽」分頁，往下捲就能看到套件、範本、插件三大區"},{"icon":"📊","title":"用上方分類卡聚焦","desc":"點頂部的套件、範本、插件、影片數字卡，快速定位你想找的類型"},{"icon":"⬇️","title":"安裝或套用","desc":"套件按「安裝套件」、範本按「使用範本」進訓練場、插件滑過按「安裝」"},{"icon":"🧪","title":"到我的試用管理","desc":"切到「我的試用」分頁，集中查看試用中的資源"}],
    voice: "歡迎來到資源中心，這裡是 Agent School 專屬的應用商店，你不必從一行程式碼開始，可以把別人做好的零件直接拿來用。最上面有四張分類卡，分別是應用套件、場景範本、擴充插件和教學影片，點一下就能快速聚焦。第一區是應用套件，共六款，像是一鍵建知識庫的 RAG 套件、五分鐘讓機器人在 LINE 上線的部署包，每張卡片都標了作者、版本和安裝數，按下安裝套件就會加進你的工作台。第二區是場景範本，有六種現成工作流，例如每日新聞摘要推播、客服自動分流，按使用範本就會帶你到訓練場套用。第三區是 Chrome 擴充插件，滑鼠移過去就會出現安裝鈕。標了熱門代表大家都在用，標可試用的可以先試玩再決定。最後上方還有我的試用分頁，方便你管理試用中的資源。挑個順眼的，現在就開始組裝你的 AI 特工吧。",
  },
  "/materials": {
    emoji: "📄",
    title: "補充教材",
    tagline: "延伸學習資源庫，把各項 Agent 應用主題學得更深更透",
    svg: scene("<rect x=\"46\" y=\"40\" width=\"308\" height=\"36\" rx=\"10\" fill=\"url(#pp)\" opacity=\"0.9\"/><text x=\"62\" y=\"63\" font-size=\"18\">📄</text><rect x=\"92\" y=\"50\" width=\"120\" height=\"7\" rx=\"3.5\" fill=\"#fff\" opacity=\"0.92\"/><rect x=\"92\" y=\"63\" width=\"180\" height=\"5\" rx=\"2.5\" fill=\"#fff\" opacity=\"0.5\"/><g><rect x=\"46\" y=\"92\" width=\"308\" height=\"34\" rx=\"9\" fill=\"#fff\" opacity=\"0.06\" stroke=\"#a855f7\" stroke-opacity=\"0.4\"/><text x=\"58\" y=\"115\" font-size=\"15\">📖</text><rect x=\"84\" y=\"100\" width=\"96\" height=\"6\" rx=\"3\" fill=\"#fff\" opacity=\"0.85\"/><rect x=\"84\" y=\"112\" width=\"150\" height=\"5\" rx=\"2.5\" fill=\"#fff\" opacity=\"0.45\"/><rect x=\"296\" y=\"101\" width=\"46\" height=\"16\" rx=\"8\" fill=\"#22c55e\" opacity=\"0.22\" stroke=\"#22c55e\" stroke-opacity=\"0.5\"/><rect x=\"304\" y=\"107\" width=\"30\" height=\"5\" rx=\"2.5\" fill=\"#22c55e\" opacity=\"0.9\"/></g><g><rect x=\"46\" y=\"132\" width=\"308\" height=\"34\" rx=\"9\" fill=\"#fff\" opacity=\"0.06\" stroke=\"#22d3ee\" stroke-opacity=\"0.4\"/><text x=\"58\" y=\"155\" font-size=\"15\">🎯</text><rect x=\"84\" y=\"140\" width=\"80\" height=\"6\" rx=\"3\" fill=\"#fff\" opacity=\"0.85\"/><rect x=\"84\" y=\"152\" width=\"160\" height=\"5\" rx=\"2.5\" fill=\"#fff\" opacity=\"0.45\"/><rect x=\"288\" y=\"141\" width=\"54\" height=\"16\" rx=\"8\" fill=\"#a855f7\" opacity=\"0.22\" stroke=\"#a855f7\" stroke-opacity=\"0.5\"/><rect x=\"296\" y=\"147\" width=\"38\" height=\"5\" rx=\"2.5\" fill=\"#a855f7\" opacity=\"0.9\"/></g><g><rect x=\"46\" y=\"172\" width=\"308\" height=\"34\" rx=\"9\" fill=\"#fff\" opacity=\"0.06\" stroke=\"#eab308\" stroke-opacity=\"0.4\"/><text x=\"58\" y=\"195\" font-size=\"15\">💰</text><rect x=\"84\" y=\"180\" width=\"104\" height=\"6\" rx=\"3\" fill=\"#fff\" opacity=\"0.85\"/><rect x=\"84\" y=\"192\" width=\"140\" height=\"5\" rx=\"2.5\" fill=\"#fff\" opacity=\"0.45\"/><rect x=\"300\" y=\"181\" width=\"42\" height=\"16\" rx=\"8\" fill=\"#eab308\" opacity=\"0.22\" stroke=\"#eab308\" stroke-opacity=\"0.5\"/><rect x=\"308\" y=\"187\" width=\"26\" height=\"5\" rx=\"2.5\" fill=\"#eab308\" opacity=\"0.9\"/></g>"),
    whatIs: "這頁是 Agent School 的「延伸學習資源庫」。上課之外，你想再往下深挖某個主題時，這裡幫你準備好六份精選教材，從 Agent Prompt 實戰手冊、Make.com 串接速查表、Dify 知識庫建置，到 Agent Skill 模板庫、CrewAI 多 Agent 範例集，還有最受歡迎的變現案例庫。每份都標好「免費、學員專屬、進階」三種等級，讓你一眼知道哪些現在就能拿、哪些是學員福利、哪些是進階挑戰。想學的主題還沒看到，也能直接提建議讓我們補上。",
    features: [{"icon":"📚","text":"六份精選教材一字排開：Prompt 手冊、Make.com 速查表、Dify 建置、Skill 模板、CrewAI 範例、變現案例"},{"icon":"🏷️","text":"每份標示等級標籤——綠色「免費」、紫色「學員專屬」、橘色「進階」，一眼分辨取用門檻"},{"icon":"📨","text":"游標移到卡片上會浮出「前往 →」按鈕，按下後提示完整教材內容將寄送到你的信箱"},{"icon":"✍️","text":"底部「提出教材建議」按鈕，想學的主題沒看到就直接許願，送出後會收到確認"}],
    steps: [{"icon":"👀","title":"瀏覽教材清單","desc":"由上往下看六張卡片，讀標題和一句說明，找到你現在想加強的主題"},{"icon":"🏷️","title":"看懂等級標籤","desc":"綠色免費隨手拿、紫色學員專屬、橘色進階挑戰，依自己的階段挑合適的"},{"icon":"📨","title":"點「前往 →」領取","desc":"把游標移到卡片上，按下右側浮出的按鈕，系統提示完整內容會寄送到你的信箱"},{"icon":"✍️","title":"沒看到就許願","desc":"滑到最底，點「提出教材建議」，告訴我們你想學的主題，等補上新教材"}],
    voice: "歡迎來到補充教材頁，這裡是 Agent School 的延伸學習資源庫。當你上完課，想針對某個主題再往下深挖的時候，這一頁就幫你把精選的教材都準備好了。往下看，你會看到六份教材一張一張排開，從 Agent Prompt 實戰手冊、Make.com 串接速查表、Dify 知識庫建置教學，到 Agent Skill 模板庫、CrewAI 多 Agent 範例集，還有最受歡迎的變現案例庫，每一份左邊都有一個小圖示，右邊配上一句說明，讓你一眼就知道內容在講什麼。注意看標題旁邊的小標籤，綠色的代表免費、現在就能拿，紫色的是學員專屬福利，橘色的則是進階挑戰，你可以依自己目前的程度來挑。找到想學的主題之後，把游標移到那張卡片上，右側就會浮出前往按鈕，按下去之後系統會提示你，完整的內容會寄送到你的信箱。如果你想學的主題還沒出現，別擔心，滑到最下面點一下提出教材建議，把你的需求告訴我們，送出之後就會收到確認，之後我們會把新教材補上。",
  },
  "/events": {
    emoji: "🎪",
    title: "活動報名",
    tagline: "講座、說明會、研討會、工作坊一站式報名",
    svg: scene("<rect x=\"40\" y=\"40\" width=\"200\" height=\"92\" rx=\"14\" fill=\"#fff\" opacity=\"0.06\" stroke=\"#a855f7\" stroke-opacity=\"0.45\"/>\n<rect x=\"54\" y=\"54\" width=\"92\" height=\"8\" rx=\"4\" fill=\"#fff\" opacity=\"0.85\"/>\n<rect x=\"162\" y=\"52\" width=\"44\" height=\"16\" rx=\"8\" fill=\"#22c55e\" opacity=\"0.85\"/>\n<text x=\"170\" y=\"64\" font-size=\"9\" fill=\"#0b0b12\">免費</text>\n<rect x=\"54\" y=\"72\" width=\"150\" height=\"5\" rx=\"2.5\" fill=\"#fff\" opacity=\"0.4\"/>\n<rect x=\"54\" y=\"82\" width=\"120\" height=\"5\" rx=\"2.5\" fill=\"#fff\" opacity=\"0.25\"/>\n<text x=\"54\" y=\"106\" font-size=\"10\" fill=\"#22d3ee\">📅 07/10</text>\n<text x=\"120\" y=\"106\" font-size=\"10\" fill=\"#eab308\">👥 34/80</text>\n<rect x=\"54\" y=\"114\" width=\"172\" height=\"8\" rx=\"4\" fill=\"#fff\" opacity=\"0.12\"/>\n<rect x=\"54\" y=\"114\" width=\"74\" height=\"8\" rx=\"4\" fill=\"url(#pp)\"/>\n<rect x=\"262\" y=\"40\" width=\"98\" height=\"92\" rx=\"14\" fill=\"#fff\" opacity=\"0.06\" stroke=\"#ec4899\" stroke-opacity=\"0.45\"/>\n<rect x=\"276\" y=\"54\" width=\"60\" height=\"7\" rx=\"3.5\" fill=\"#fff\" opacity=\"0.8\"/>\n<rect x=\"276\" y=\"68\" width=\"70\" height=\"5\" rx=\"2.5\" fill=\"#fff\" opacity=\"0.35\"/>\n<rect x=\"276\" y=\"82\" width=\"70\" height=\"9\" rx=\"4.5\" fill=\"#ef4444\" opacity=\"0.25\"/>\n<rect x=\"276\" y=\"82\" width=\"62\" height=\"9\" rx=\"4.5\" fill=\"#ef4444\" opacity=\"0.85\"/>\n<text x=\"276\" y=\"106\" font-size=\"9\" fill=\"#ef4444\">⚠ 即將額滿</text>\n<rect x=\"276\" y=\"112\" width=\"70\" height=\"14\" rx=\"7\" fill=\"url(#bl)\" opacity=\"0.9\"/>\n<rect x=\"40\" y=\"156\" width=\"160\" height=\"44\" rx=\"12\" fill=\"#fff\" opacity=\"0.05\" stroke=\"#6366f1\" stroke-opacity=\"0.35\"/>\n<circle cx=\"62\" cy=\"178\" r=\"13\" fill=\"url(#pp)\" opacity=\"0.9\"/>\n<path d=\"M57 172 l11 6 l-11 6 z\" fill=\"#fff\"/>\n<rect x=\"84\" y=\"170\" width=\"80\" height=\"6\" rx=\"3\" fill=\"#fff\" opacity=\"0.45\"/>\n<rect x=\"84\" y=\"182\" width=\"56\" height=\"5\" rx=\"2.5\" fill=\"#fff\" opacity=\"0.25\"/>\n<text x=\"216\" y=\"178\" font-size=\"11\" fill=\"#fff\" opacity=\"0.5\">歷史活動 · 回放</text>\n<text x=\"332\" y=\"200\" font-size=\"26\">🎟️</text>"),
    whatIs: "這頁是 Agent School 的活動中心，把所有講座、說明會、研討會和工作坊集中到一個地方，讓你不用四處找報名連結。想了解課程架構就來招生說明會，想學賺錢實戰就看主題講座，想動手做就報名小班工作坊。每場活動都標明日期、時間、形式、費用和剩餘名額，看到喜歡的當場一鍵報名；錯過了也沒關係，歷史活動區還能看參加人數並點回放補課。",
    features: [{"icon":"📋","text":"「即將舉辦」列出三場活動：招生說明會、主題講座與實體小班工作坊"},{"icon":"🏷️","text":"每場標示免費或付費（如 NT$2800），以及線上／實體的活動形式、日期與時間"},{"icon":"📊","text":"名額進度條即時顯示已報名／總名額，超過八成自動跳出「名額即將額滿」紅字提醒"},{"icon":"✅","text":"一鍵「立即報名」，按下後變成「已報名」並提示開課前以 Email 通知"},{"icon":"🎬","text":"「歷史活動」區顯示過去場次的參加人數，可點「看回放」重溫已結束的活動"}],
    steps: [{"icon":"👀","title":"瀏覽活動","desc":"在「即將舉辦」看每場的日期、時間、形式與費用"},{"icon":"📊","title":"確認名額","desc":"看進度條剩多少位，紅字提醒代表快額滿了要快"},{"icon":"✅","title":"立即報名","desc":"點按鈕完成報名，開課前會收到 Email 通知"},{"icon":"🎬","title":"看回放","desc":"錯過的場次到「歷史活動」點看回放補課"}],
    voice: "歡迎來到活動報名中心，這裡把所有講座、說明會、研討會和工作坊都集中在一起，一站就能報名。最上面的即將舉辦區，第一場是 Agent School 招生說明會，免費的，帶你了解五階段課程架構跟就業方向；第二場是主題講座，分享學員怎麼用 Agent 每月多賺五萬；第三場是實體的多 Agent 工作坊，小班制要兩千八百元，手把手帶你做系統。每張卡片都會清楚標示日期、時間、是線上還是實體，還有費用是免費還是付費。特別注意中間那條名額進度條，它會即時顯示已經有多少人報名，一旦超過八成滿，就會跳出名額即將額滿的紅色提醒，看到就要把握。看到喜歡的活動，直接按右邊的立即報名，按完會變成已報名，開課前我們會用 Email 通知你。如果你錯過了哪一場，往下捲到歷史活動區，這裡有過去場次的參加人數，點看回放就能重新補課。",
  },
  "/community": {
    emoji: "💬",
    title: "交流中心",
    tagline: "和同學分享心得、提問、揪團，一起把 Agent 玩到極致",
    svg: scene("<rect x=\"40\" y=\"40\" width=\"150\" height=\"30\" rx=\"8\" fill=\"#fff\" opacity=\"0.06\" stroke=\"#a855f7\" stroke-opacity=\"0.4\"/>\n<circle cx=\"58\" cy=\"55\" r=\"8\" fill=\"url(#pp)\"/>\n<rect x=\"74\" y=\"50\" width=\"42\" height=\"5\" rx=\"2.5\" fill=\"#fff\" opacity=\"0.7\"/>\n<rect x=\"74\" y=\"59\" width=\"60\" height=\"4\" rx=\"2\" fill=\"#fff\" opacity=\"0.35\"/>\n<rect x=\"210\" y=\"40\" width=\"150\" height=\"30\" rx=\"8\" fill=\"#fff\" opacity=\"0.06\" stroke=\"#22d3ee\" stroke-opacity=\"0.4\"/>\n<circle cx=\"228\" cy=\"55\" r=\"8\" fill=\"url(#bl)\"/>\n<rect x=\"244\" y=\"50\" width=\"42\" height=\"5\" rx=\"2.5\" fill=\"#fff\" opacity=\"0.7\"/>\n<rect x=\"244\" y=\"59\" width=\"66\" height=\"4\" rx=\"2\" fill=\"#fff\" opacity=\"0.35\"/>\n<rect x=\"40\" y=\"86\" width=\"320\" height=\"78\" rx=\"12\" fill=\"#fff\" opacity=\"0.07\" stroke=\"#ec4899\" stroke-opacity=\"0.35\"/>\n<circle cx=\"64\" cy=\"108\" r=\"11\" fill=\"url(#pp)\"/>\n<text x=\"58\" y=\"113\" font-size=\"12\">🤖</text>\n<rect x=\"84\" y=\"100\" width=\"70\" height=\"6\" rx=\"3\" fill=\"#fff\" opacity=\"0.75\"/>\n<rect x=\"162\" y=\"99\" width=\"58\" height=\"14\" rx=\"7\" fill=\"#a855f7\" opacity=\"0.22\" stroke=\"#a855f7\" stroke-opacity=\"0.4\"/>\n<rect x=\"170\" y=\"103\" width=\"42\" height=\"5\" rx=\"2.5\" fill=\"#a855f7\" opacity=\"0.9\"/>\n<rect x=\"84\" y=\"118\" width=\"256\" height=\"5\" rx=\"2.5\" fill=\"#fff\" opacity=\"0.35\"/>\n<rect x=\"84\" y=\"129\" width=\"220\" height=\"5\" rx=\"2.5\" fill=\"#fff\" opacity=\"0.35\"/>\n<rect x=\"84\" y=\"146\" width=\"44\" height=\"12\" rx=\"6\" fill=\"#fff\" opacity=\"0.08\"/>\n<text x=\"89\" y=\"155\" font-size=\"9\">👍 14</text>\n<rect x=\"136\" y=\"146\" width=\"58\" height=\"12\" rx=\"6\" fill=\"#fff\" opacity=\"0.08\"/>\n<text x=\"141\" y=\"155\" font-size=\"9\">💬 5 則</text>\n<text x=\"316\" y=\"202\" font-size=\"28\">💬</text>"),
    whatIs: "交流中心是 Agent School 的學員社群，你在這裡不再是一個人練功。把學到的心得、孵出來的 Agent、接到的案子貼出來，跟同學互相按讚、討論；卡關的時候也能直接發問，總有人懂你踩的坑。它讓孤單的線上學習變成有溫度的同行，從新手到接案高手都能在這裡找到同伴和靈感。",
    features: [{"icon":"📂","text":"六大頻道分類：自我介紹、學習心得、提問求助、Agent 展示、接案分享、公告，每個都標了貼文數"},{"icon":"📰","text":"貼文動態牆，顯示同學的頭像、所屬頻道、發文時間與內容"},{"icon":"👍","text":"一鍵按讚貼文，數字會即時加一給你回饋"},{"icon":"💬","text":"每則貼文顯示回覆數，可點開查看（留言功能開發中）"},{"icon":"🤖","text":"真實情境貼文：從孵出第一隻 Agent、RAG 直播筆記到第一筆接案報價分享"}],
    steps: [{"icon":"📂","title":"挑頻道","desc":"從上方六個頻道選一個進去，例如提問求助或 Agent 展示"},{"icon":"📰","title":"逛動態","desc":"往下滑看同學最新的貼文、心得與接案分享"},{"icon":"👍","title":"按讚互動","desc":"看到喜歡的內容點讚，按鈕數字會立刻加一"},{"icon":"💬","title":"點開回覆","desc":"點回覆數查看討論互動，加入大家的對話"}],
    voice: "歡迎來到交流中心，這裡是 Agent School 的學員社群，學習不再是一個人埋頭苦練。先看最上面這一排，總共有六個頻道，分別是自我介紹、學習心得、提問求助、Agent 展示、接案分享，還有公告，每個頻道旁邊都標了目前的貼文數量，你想看什麼主題，點進去就對了。其中提問求助最熱鬧，有四十一則貼文，卡關的時候在這裡發問，總會有同學幫你解答。往下滑就是貼文動態牆，每一則都看得到發文同學的頭像、所屬頻道和發文時間。你會看到有人分享孵出了第一隻 Agent 財務小管家，有人整理了 RAG 直播的筆記，也有人秀出第一筆接案的報價心得。看到喜歡的內容，按下讚，數字會馬上加一；想參與討論，點開回覆數就能加入大家的對話。在這裡，你的每一個進步都有人看見，每一個問題都有人接住。",
  },
  "/showcase": {
    emoji: "🏆",
    title: "成果展示",
    tagline: "看學長姐的 Agent 怎麼上線實戰，找到你的下一個靈感",
    svg: scene("<rect x=\"40\" y=\"38\" width=\"150\" height=\"78\" rx=\"12\" fill=\"#fff\" opacity=\"0.06\" stroke=\"#a855f7\" stroke-opacity=\"0.4\"/><circle cx=\"64\" cy=\"62\" r=\"13\" fill=\"url(#pp)\"/><text x=\"57\" y=\"68\" font-size=\"14\">🤖</text><rect x=\"86\" y=\"52\" width=\"78\" height=\"7\" rx=\"3.5\" fill=\"#fff\" opacity=\"0.85\"/><rect x=\"86\" y=\"64\" width=\"54\" height=\"5\" rx=\"2.5\" fill=\"#fff\" opacity=\"0.45\"/><rect x=\"52\" y=\"84\" width=\"40\" height=\"11\" rx=\"5.5\" fill=\"#a855f7\" opacity=\"0.25\" stroke=\"#a855f7\" stroke-opacity=\"0.4\"/><rect x=\"98\" y=\"84\" width=\"40\" height=\"11\" rx=\"5.5\" fill=\"#fff\" opacity=\"0.08\" stroke=\"#fff\" stroke-opacity=\"0.12\"/><text x=\"50\" y=\"110\" font-size=\"11\" fill=\"#ec4899\">❤️</text><rect x=\"66\" y=\"103\" width=\"22\" height=\"6\" rx=\"3\" fill=\"#fff\" opacity=\"0.4\"/><rect x=\"210\" y=\"38\" width=\"150\" height=\"78\" rx=\"12\" fill=\"#fff\" opacity=\"0.06\" stroke=\"#22d3ee\" stroke-opacity=\"0.4\"/><circle cx=\"234\" cy=\"62\" r=\"13\" fill=\"url(#bl)\"/><text x=\"227\" y=\"68\" font-size=\"14\">🤖</text><rect x=\"256\" y=\"52\" width=\"78\" height=\"7\" rx=\"3.5\" fill=\"#fff\" opacity=\"0.85\"/><rect x=\"256\" y=\"64\" width=\"54\" height=\"5\" rx=\"2.5\" fill=\"#fff\" opacity=\"0.45\"/><rect x=\"222\" y=\"84\" width=\"40\" height=\"11\" rx=\"5.5\" fill=\"#22d3ee\" opacity=\"0.22\" stroke=\"#22d3ee\" stroke-opacity=\"0.4\"/><rect x=\"268\" y=\"84\" width=\"40\" height=\"11\" rx=\"5.5\" fill=\"#fff\" opacity=\"0.08\" stroke=\"#fff\" stroke-opacity=\"0.12\"/><text x=\"220\" y=\"110\" font-size=\"11\" fill=\"#ec4899\">❤️</text><rect x=\"236\" y=\"103\" width=\"22\" height=\"6\" rx=\"3\" fill=\"#fff\" opacity=\"0.4\"/><g transform=\"translate(150,138)\"><rect x=\"0\" y=\"0\" width=\"100\" height=\"50\" rx=\"14\" fill=\"url(#pp)\" opacity=\"0.92\"/><text x=\"34\" y=\"33\" font-size=\"22\">🏆</text><rect x=\"62\" y=\"18\" width=\"26\" height=\"6\" rx=\"3\" fill=\"#fff\" opacity=\"0.9\"/><rect x=\"62\" y=\"30\" width=\"20\" height=\"5\" rx=\"2.5\" fill=\"#fff\" opacity=\"0.55\"/></g><circle cx=\"70\" cy=\"198\" r=\"6\" fill=\"#22c55e\"/><rect x=\"84\" y=\"195\" width=\"46\" height=\"6\" rx=\"3\" fill=\"#fff\" opacity=\"0.4\"/><circle cx=\"270\" cy=\"198\" r=\"6\" fill=\"#eab308\"/><rect x=\"284\" y=\"195\" width=\"46\" height=\"6\" rx=\"3\" fill=\"#fff\" opacity=\"0.4\"/>"),
    whatIs: "這裡是學員的「實戰榮譽榜」。光看課程不知道訓練好的 Agent 到底能做什麼？這頁直接把學長姐的畢業作品攤開給你看：每一張卡片都是一個真的在跑的 Agent，包含它的名字、主人、目前等級、會哪些技能，還有最重要的——它實際解決了什麼問題、跑了多久、成效如何。對新學員來說，這是最快找到靈感、確認「我也做得到」的地方。",
    features: [{"icon":"🤖","text":"四個真實學員作品卡：小助理 Aria、銷售小幫手 SalesBot、客服天使 Angel、財務管家 MoneyBot"},{"icon":"🏷️","text":"每張卡標示主人、訓練等級（Lv.2 成長期到 Lv.5 畢業期）與應用分類（生活助手 / 商業應用 / 業務客服 / 辦公流程）"},{"icon":"🧩","text":"技能標籤一目了然：搜尋、知識庫、LINE、CRM、Email、記憶、試算表、排程"},{"icon":"❤️","text":"按讚支持喜歡的作品，點下去讚數即時 +1（示範互動）"},{"icon":"🔍","text":"點「查看詳情」彈出該 Agent 的實戰成果說明"}],
    steps: [{"icon":"👀","title":"瀏覽作品","desc":"看四張學員 Agent 卡片，了解它們各自解決什麼問題"},{"icon":"🏷️","title":"對照技能","desc":"看技能標籤與等級，想想哪些組合適合你自己的需求"},{"icon":"❤️","title":"按讚與看詳情","desc":"點愛心支持、點「查看詳情」深入了解某個作品的成效"},{"icon":"🎓","title":"換你上榜","desc":"點底部「去訓練我的 Agent」，完成訓練後也來展示你的作品"}],
    voice: "歡迎來到成果展示，這裡是學員的實戰榮譽榜。如果你還在想，訓練好一個 Agent 到底能拿來做什麼，那這一頁就是最好的答案。畫面上有四個真的在運作的學員作品。像是小助理 Aria，每天早上自動幫主人摘要十則科技新聞，再推播到 LINE，已經穩定跑了三十天。還有銷售小幫手 SalesBot，幫保險業務員自動追蹤五十位客戶，每週產出拜訪提醒跟報價書。每一張卡片都會告訴你這個 Agent 的主人是誰、目前在哪個訓練等級、會哪些技能，還有它實際的成效。看到喜歡的作品，可以點下愛心幫他按讚，讚數會馬上加一；想多了解，就點查看詳情，會跳出這個作品的實戰成果說明。逛完之後，如果你也想讓自己的作品上榜，就點最下面的去訓練我的 Agent，完成訓練後，這裡就有你的位置。",
  },
  "/points": {
    emoji: "🪙",
    title: "我的點數",
    tagline: "學習點數、任務積分、累計收益，一頁看清你的三本帳",
    svg: scene("<g transform=\"translate(40,40)\"><rect x=\"0\" y=\"0\" width=\"96\" height=\"64\" rx=\"12\" fill=\"#fff\" opacity=\"0.06\" stroke=\"#a855f7\" stroke-opacity=\"0.45\"/><text x=\"14\" y=\"34\" font-size=\"22\">🪙</text><rect x=\"14\" y=\"44\" width=\"50\" height=\"6\" rx=\"3\" fill=\"#fff\" opacity=\"0.7\"/><rect x=\"14\" y=\"54\" width=\"36\" height=\"5\" rx=\"2.5\" fill=\"#fff\" opacity=\"0.35\"/></g><g transform=\"translate(152,40)\"><rect x=\"0\" y=\"0\" width=\"96\" height=\"64\" rx=\"12\" fill=\"#fff\" opacity=\"0.06\" stroke=\"#22d3ee\" stroke-opacity=\"0.45\"/><text x=\"14\" y=\"34\" font-size=\"22\">🎯</text><rect x=\"14\" y=\"44\" width=\"50\" height=\"6\" rx=\"3\" fill=\"#fff\" opacity=\"0.7\"/><rect x=\"14\" y=\"54\" width=\"30\" height=\"5\" rx=\"2.5\" fill=\"#fff\" opacity=\"0.35\"/></g><g transform=\"translate(264,40)\"><rect x=\"0\" y=\"0\" width=\"96\" height=\"64\" rx=\"12\" fill=\"#fff\" opacity=\"0.06\" stroke=\"#22c55e\" stroke-opacity=\"0.5\"/><text x=\"14\" y=\"34\" font-size=\"22\">💰</text><rect x=\"14\" y=\"44\" width=\"56\" height=\"6\" rx=\"3\" fill=\"#22c55e\" opacity=\"0.8\"/><rect x=\"14\" y=\"54\" width=\"34\" height=\"5\" rx=\"2.5\" fill=\"#fff\" opacity=\"0.35\"/></g><g transform=\"translate(40,124)\"><rect x=\"0\" y=\"0\" width=\"320\" height=\"78\" rx=\"12\" fill=\"#fff\" opacity=\"0.05\" stroke=\"url(#pp)\" stroke-opacity=\"0.5\"/><rect x=\"14\" y=\"14\" width=\"100\" height=\"6\" rx=\"3\" fill=\"#fff\" opacity=\"0.7\"/><rect x=\"14\" y=\"26\" width=\"150\" height=\"5\" rx=\"2.5\" fill=\"#fff\" opacity=\"0.3\"/><rect x=\"14\" y=\"44\" width=\"120\" height=\"6\" rx=\"3\" fill=\"#fff\" opacity=\"0.7\"/><rect x=\"14\" y=\"56\" width=\"160\" height=\"5\" rx=\"2.5\" fill=\"#fff\" opacity=\"0.3\"/><rect x=\"262\" y=\"14\" width=\"44\" height=\"16\" rx=\"8\" fill=\"#22c55e\" opacity=\"0.85\"/><rect x=\"270\" y=\"20\" width=\"28\" height=\"5\" rx=\"2.5\" fill=\"#0d0820\" opacity=\"0.7\"/><rect x=\"262\" y=\"44\" width=\"44\" height=\"16\" rx=\"8\" fill=\"#22c55e\" opacity=\"0.85\"/><rect x=\"270\" y=\"50\" width=\"28\" height=\"5\" rx=\"2.5\" fill=\"#0d0820\" opacity=\"0.7\"/></g>"),
    whatIs: "這一頁就是你在 Agent School 的「點數總帳」。你在學校裡的努力會變成三種價值：上課與結業拿到的學習點數、接任務累積的任務積分，還有真正入帳的現金收益。它把這三本帳整理在同一頁，再附上一條清楚的點數紀錄，讓你不用猜「這些點數到底哪來的」，一眼就知道自己學了多少、做了多少、賺了多少。",
    features: [{"icon":"🪙","text":"學習點數：目前 350 點，來自課程與結業，標示可兌換好禮"},{"icon":"🎯","text":"任務積分：目前 50 分，靠接案任務累積"},{"icon":"💰","text":"累計收益：NT$8,000 現金獎勵，標示已入帳"},{"icon":"📜","text":"點數紀錄：每筆列出來源類別、說明與日期"},{"icon":"🟢","text":"增減數值用綠色標示，進帳一眼看得出來"}],
    steps: [{"icon":"👀","title":"先看三張卡","desc":"上方學習點數、任務積分、累計收益，掌握三本帳的當前數字"},{"icon":"📜","title":"往下看紀錄","desc":"點數紀錄區列出每一筆的說明、來源類別與日期"},{"icon":"🔍","title":"對照來源","desc":"看是手動發放、課程完成還是任務積分，了解點數怎麼來的"},{"icon":"🎁","title":"規劃兌換","desc":"知道學習點數可兌換好禮後，安排怎麼把累積花在刀口上"}],
    voice: "歡迎來到我的點數，這裡是你在 Agent School 的點數總帳。你在學校裡的付出，會變成三種不一樣的價值，所以最上面有三張卡片。第一張是學習點數，目前是三百五十點，主要來自上課和結業，可以拿來兌換好禮。第二張是任務積分，現在是五十分，這是你接案、做任務一筆一筆累積起來的。第三張是累計收益，新台幣八千元，這是真正入帳的現金獎勵。看完這三張卡，再往下就是點數紀錄。每一筆都寫得清清楚楚，像是入學歡迎禮加兩百點、孵化期結業加一百點，還有電商客服任務加五十點，旁邊都標了來源類別和日期。增加的數字用綠色顯示，所以哪裡進帳一眼就看得到。簡單說，這頁就是讓你不用猜，學了多少、做了多少、賺了多少，全部攤在這一頁。",
  },
  "/redeem": {
    emoji: "🎁",
    title: "兌換中心",
    tagline: "把學習累積的點數，換成課程折抵、訓練權益與實體好禮",
    svg: scene("<rect x=\"150\" y=\"40\" width=\"120\" height=\"44\" rx=\"22\" fill=\"#fff\" opacity=\"0.06\" stroke=\"#eab308\" stroke-opacity=\"0.5\"/>\n<circle cx=\"178\" cy=\"62\" r=\"13\" fill=\"#eab308\"/>\n<text x=\"171\" y=\"68\" font-size=\"15\">🪙</text>\n<rect x=\"200\" y=\"54\" width=\"58\" height=\"7\" rx=\"3.5\" fill=\"#eab308\" opacity=\"0.9\"/>\n<rect x=\"200\" y=\"66\" width=\"40\" height=\"5\" rx=\"2.5\" fill=\"#fff\" opacity=\"0.4\"/>\n<g>\n  <rect x=\"40\" y=\"104\" width=\"100\" height=\"74\" rx=\"12\" fill=\"#fff\" opacity=\"0.06\" stroke=\"#a855f7\" stroke-opacity=\"0.45\"/>\n  <text x=\"56\" y=\"134\" font-size=\"20\">🎓</text>\n  <rect x=\"52\" y=\"146\" width=\"62\" height=\"6\" rx=\"3\" fill=\"#fff\" opacity=\"0.5\"/>\n  <rect x=\"52\" y=\"158\" width=\"40\" height=\"6\" rx=\"3\" fill=\"url(#pp)\"/>\n</g>\n<g>\n  <rect x=\"150\" y=\"104\" width=\"100\" height=\"74\" rx=\"12\" fill=\"#fff\" opacity=\"0.06\" stroke=\"#22d3ee\" stroke-opacity=\"0.45\"/>\n  <text x=\"166\" y=\"134\" font-size=\"20\">☕</text>\n  <rect x=\"162\" y=\"146\" width=\"62\" height=\"6\" rx=\"3\" fill=\"#fff\" opacity=\"0.5\"/>\n  <rect x=\"162\" y=\"158\" width=\"40\" height=\"6\" rx=\"3\" fill=\"url(#bl)\"/>\n</g>\n<g>\n  <rect x=\"260\" y=\"104\" width=\"100\" height=\"74\" rx=\"12\" fill=\"#fff\" opacity=\"0.06\" stroke=\"#ec4899\" stroke-opacity=\"0.45\"/>\n  <text x=\"276\" y=\"134\" font-size=\"20\">⌨️</text>\n  <rect x=\"272\" y=\"146\" width=\"62\" height=\"6\" rx=\"3\" fill=\"#fff\" opacity=\"0.5\"/>\n  <rect x=\"272\" y=\"158\" width=\"40\" height=\"6\" rx=\"3\" fill=\"url(#pp)\"/>\n</g>\n<path d=\"M93 91 L93 104\" stroke=\"#a855f7\" stroke-width=\"2\" stroke-opacity=\"0.5\"/>\n<path d=\"M200 91 L200 104\" stroke=\"#22d3ee\" stroke-width=\"2\" stroke-opacity=\"0.5\"/>\n<path d=\"M307 91 L307 104\" stroke=\"#ec4899\" stroke-width=\"2\" stroke-opacity=\"0.5\"/>\n<circle cx=\"320\" cy=\"196\" r=\"11\" fill=\"#ef4444\" opacity=\"0.85\"/>\n<text x=\"313\" y=\"201\" font-size=\"11\" fill=\"#fff\" font-weight=\"bold\">3</text>"),
    whatIs: "兌換中心是你把努力變成回饋的地方。你在 Agent School 學習打卡、完成任務、考取認證所累積的點數，到這裡就能花掉。頁面最上方會顯示你目前的可用點數，下方則把所有獎品分門別類陳列，從省錢的課程折抵券、能加速成長的訓練權益，到馬克杯、聯名 T 恤這類拿在手上的實體好禮通通有。點數夠就能直接兌換，點數還不夠也會清楚告訴你還差多少，讓你知道再衝一下就能入手。",
    features: [{"icon":"🪙","text":"頂部點數儀表板：顯示目前可用點數（示範為 350 點），並提示學習打卡、完成任務、考取認證皆可累積"},{"icon":"🗂️","text":"獎品分五大類：課程折抵、訓練權益、專屬服務、VIP 權益、實體好禮"},{"icon":"🎁","text":"八款獎品從 NT$500 折抵券、優先訓練券、技能包加速、1-on-1 諮詢、VIP 學員，到馬克杯與限量機械鍵盤都有"},{"icon":"📦","text":"每件商品標示庫存狀態，剩 10 件以內顯示「剩 N」，否則顯示「充足」"},{"icon":"⚖️","text":"點數足夠（≤350）顯示「兌換」按鈕，不足則變灰並提示「還差幾點」，引導你去累積點數"}],
    steps: [{"icon":"🪙","title":"先看點數","desc":"最上方確認自己目前有多少可用點數"},{"icon":"🗂️","title":"逛分類","desc":"往下瀏覽課程折抵、訓練權益到實體好禮等五大類獎品"},{"icon":"📦","title":"看清楚再下手","desc":"留意每件好禮的所需點數與庫存狀態，限量品手刀搶"},{"icon":"🎁","title":"點下兌換","desc":"點數夠就按「兌換」完成；不足會提示還差幾點"}],
    voice: "歡迎來到兌換中心，這裡是你把學習成果換成實際回饋的地方。你平常在學校裡學習打卡、完成任務、考取認證所累積的點數，到這邊就能花掉。先看畫面最上方那個金色的點數儀表板，它會顯示你目前的可用點數，示範帳號是三百五十點。往下滑，所有獎品都依照類別整齊陳列，分成課程折抵、訓練權益、專屬服務、VIP 權益，還有實體好禮五大類。獎品很豐富，從一張省五百塊的課程折抵券、能讓你的 Agent 優先訓練的權益、技能包加速解鎖，到一對一諮詢，甚至是限量的機械鍵盤跟聯名 T 恤都有。每件商品旁邊都會標示需要多少點數跟庫存還剩多少，特別熱門的限量品數量很少，看到喜歡的要快。如果點數夠，直接按下兌換就完成了；要是還不夠，按鈕會變灰，並告訴你還差幾點，提醒你再去完成任務或考認證補一補。",
  },
  "/pricing": {
    emoji: "💎",
    title: "方案與定價",
    tagline: "學費不是成本，是投資，你的 Agent 上市後賺得回來",
    svg: scene("<text x=\"158\" y=\"38\" font-size=\"20\">🔄</text>\n<text x=\"40\" y=\"50\" font-size=\"9\" fill=\"#fff\" opacity=\"0.55\">Learn</text>\n<text x=\"184\" y=\"40\" font-size=\"10\" fill=\"#22c55e\" font-weight=\"bold\">Earn 飛輪</text>\n<line x1=\"64\" y1=\"52\" x2=\"118\" y2=\"52\" stroke=\"#a855f7\" stroke-width=\"2\" stroke-dasharray=\"4 4\" opacity=\"0.7\"/>\n<line x1=\"248\" y1=\"52\" x2=\"300\" y2=\"52\" stroke=\"#22d3ee\" stroke-width=\"2\" stroke-dasharray=\"4 4\" opacity=\"0.7\"/>\n<rect x=\"32\" y=\"86\" width=\"74\" height=\"100\" rx=\"12\" fill=\"#fff\" opacity=\"0.05\" stroke=\"#fff\" stroke-opacity=\"0.12\"/>\n<rect x=\"116\" y=\"78\" width=\"78\" height=\"108\" rx=\"12\" fill=\"url(#pp)\" opacity=\"0.9\"/>\n<rect x=\"204\" y=\"86\" width=\"74\" height=\"100\" rx=\"12\" fill=\"#fff\" opacity=\"0.05\" stroke=\"#eab308\" stroke-opacity=\"0.45\"/>\n<rect x=\"288\" y=\"86\" width=\"74\" height=\"100\" rx=\"12\" fill=\"#fff\" opacity=\"0.05\" stroke=\"#fff\" stroke-opacity=\"0.12\"/>\n<rect x=\"128\" y=\"70\" width=\"54\" height=\"15\" rx=\"7\" fill=\"url(#bl)\"/>\n<text x=\"138\" y=\"81\" font-size=\"8\" fill=\"#fff\" font-weight=\"bold\">最受歡迎</text>\n<rect x=\"44\" y=\"98\" width=\"40\" height=\"6\" rx=\"3\" fill=\"#fff\" opacity=\"0.6\"/>\n<text x=\"44\" y=\"124\" font-size=\"11\" fill=\"#fff\" font-weight=\"bold\">免費</text>\n<rect x=\"128\" y=\"98\" width=\"46\" height=\"6\" rx=\"3\" fill=\"#fff\" opacity=\"0.85\"/>\n<text x=\"128\" y=\"124\" font-size=\"11\" fill=\"#fff\" font-weight=\"bold\">$1,980</text>\n<rect x=\"216\" y=\"98\" width=\"44\" height=\"6\" rx=\"3\" fill=\"#fff\" opacity=\"0.6\"/>\n<text x=\"216\" y=\"124\" font-size=\"10\" fill=\"#eab308\" font-weight=\"bold\">學費可賺回</text>\n<rect x=\"300\" y=\"98\" width=\"40\" height=\"6\" rx=\"3\" fill=\"#fff\" opacity=\"0.6\"/>\n<text x=\"300\" y=\"124\" font-size=\"9\" fill=\"#fff\" opacity=\"0.6\" font-weight=\"bold\">企業版</text>\n<g stroke=\"#22c55e\" stroke-width=\"2\" fill=\"none\" opacity=\"0.85\">\n<path d=\"M46 140 l4 4 l7 -8\"/>\n<path d=\"M46 154 l4 4 l7 -8\"/>\n<path d=\"M130 140 l4 4 l7 -8\"/>\n<path d=\"M130 154 l4 4 l7 -8\"/>\n<path d=\"M130 168 l4 4 l7 -8\"/>\n<path d=\"M218 140 l4 4 l7 -8\"/>\n<path d=\"M218 154 l4 4 l7 -8\"/>\n<path d=\"M218 168 l4 4 l7 -8\"/>\n</g>\n<text x=\"316\" y=\"172\" font-size=\"20\">💰</text>"),
    whatIs: "這頁是 Agent School 的方案與定價中心，但它想傳達的核心觀念很特別：學費不是花掉就沒了的成本，而是一筆能賺回來的投資。最上方有個「Learn → Train → Earn 飛輪」，把你從報名上課、訓練 Agent、考取認證、上架市場、一路到賺取分潤的完整變現路徑畫成一張圖。下面排了四個方案讓你依需求挑選，最底下還放了三位真實學員的收益案例，讓你親眼看到別人多久就把學費賺了回來。",
    features: [{"icon":"🔄","text":"Learn→Train→Earn 飛輪：報名課程、訓練 Agent、考認證、上架市場、賺回學費五步驟一目了然，認證師平均 6 個月覆蓋學費"},{"icon":"🆓","text":"免費試聽方案：3 堂試聽課、孵化師概念圖鑑全覽、訓練 1 隻基礎 Agent，零元先體驗"},{"icon":"⭐","text":"學員月費 NT$1,980／月（最受歡迎）：5 期課程錄播無限看、每月 5 次訓練配額、接案資格、Agent 上架分潤 60%"},{"icon":"🏆","text":"認證師 Pro NT$28,000 一次性（學費可賺回）：無限訓練、訓練師／架構師認證、分潤 75%、1-on-1 諮詢與企業媒合"},{"icon":"📊","text":"學員真實收益案例：Sarah 入學第 4 個月賺 NT$68,000、Kevin、Nova 等，附方案與接案明細"}],
    steps: [{"icon":"🔄","title":"看懂飛輪","desc":"先讀頂部飛輪，理解學習如何一步步變成市場收入"},{"icon":"🧭","title":"挑選方案","desc":"比較免費試聽、學員月費、認證師 Pro、企業版四張卡的權益與分潤比例"},{"icon":"📈","title":"參考收益案例","desc":"看底部三位學員幾個月賺多少、靠哪種 Agent，評估投資回報"},{"icon":"🚀","title":"點按鈕入學","desc":"按方案卡的行動按鈕加入學員或申請認證，企業版則聯絡業務諮詢"}],
    voice: "歡迎來到方案與定價這一頁。這裡最想跟你說的一句話是，學費不是成本，而是一筆賺得回來的投資。先看最上面那個飛輪，它把你的成長路徑畫成五個環節，從報名課程、訓練 Agent、考取認證、上架市場，一直到最後賺回學費，認證師學員平均六個月就能靠市場收入把學費賺回來。往下是四個方案，最左邊是零元的免費試聽，可以先聽三堂課、訓練一隻基礎 Agent 體驗看看；中間掛著最受歡迎標籤的是每月一千九百八十元的學員月費，課程錄播無限看、每月有五次訓練配額，還能接案、上架抽六成分潤；橘色那張是一次付兩萬八的認證師 Pro，標榜學費可賺回，享無限訓練、進階認證和七成五分潤；最右邊則是給團隊的企業版。最後別錯過底部的真實收益案例，像 Sarah 入學第四個月就靠電商客服 Agent 賺進六萬八，看完這些數字，再點下方按鈕選擇最適合你的方案入學就行了。",
  },
  "/messages": {
    emoji: "📩",
    title: "訊息中心",
    tagline: "系統、老師、任務、同學的通知，全都收在這一頁",
    svg: scene("<rect x=\"118\" y=\"34\" width=\"120\" height=\"22\" rx=\"11\" fill=\"url(#pp)\" opacity=\"0.9\"/><text x=\"178\" y=\"50\" font-size=\"12\" fill=\"#fff\" text-anchor=\"middle\" font-family=\"sans-serif\">2 則未讀</text><g><rect x=\"40\" y=\"72\" width=\"320\" height=\"34\" rx=\"10\" fill=\"#fff\" opacity=\"0.07\" stroke=\"#a855f7\" stroke-opacity=\"0.35\"/><circle cx=\"58\" cy=\"89\" r=\"9\" fill=\"url(#pp)\"/><text x=\"58\" y=\"93\" font-size=\"9\" fill=\"#fff\" text-anchor=\"middle\" font-family=\"sans-serif\">系</text><rect x=\"74\" y=\"80\" width=\"60\" height=\"6\" rx=\"3\" fill=\"#fff\" opacity=\"0.7\"/><rect x=\"74\" y=\"92\" width=\"160\" height=\"5\" rx=\"2.5\" fill=\"#fff\" opacity=\"0.4\"/></g><g><rect x=\"40\" y=\"112\" width=\"320\" height=\"34\" rx=\"10\" fill=\"#fff\" opacity=\"0.07\" stroke=\"#22d3ee\" stroke-opacity=\"0.35\"/><circle cx=\"58\" cy=\"129\" r=\"9\" fill=\"url(#bl)\"/><text x=\"58\" y=\"133\" font-size=\"9\" fill=\"#fff\" text-anchor=\"middle\" font-family=\"sans-serif\">J</text><rect x=\"74\" y=\"120\" width=\"80\" height=\"6\" rx=\"3\" fill=\"#fff\" opacity=\"0.7\"/><rect x=\"74\" y=\"132\" width=\"150\" height=\"5\" rx=\"2.5\" fill=\"#fff\" opacity=\"0.4\"/></g><g><rect x=\"40\" y=\"152\" width=\"320\" height=\"34\" rx=\"10\" fill=\"#fff\" opacity=\"0.1\" stroke=\"#ec4899\" stroke-opacity=\"0.6\"/><circle cx=\"58\" cy=\"169\" r=\"9\" fill=\"url(#pp)\"/><text x=\"58\" y=\"173\" font-size=\"9\" fill=\"#fff\" text-anchor=\"middle\" font-family=\"sans-serif\">任</text><rect x=\"74\" y=\"160\" width=\"70\" height=\"6\" rx=\"3\" fill=\"#fff\" opacity=\"0.85\"/><rect x=\"74\" y=\"172\" width=\"170\" height=\"5\" rx=\"2.5\" fill=\"#fff\" opacity=\"0.55\"/><circle cx=\"348\" cy=\"169\" r=\"4\" fill=\"#c084fc\"/></g><text x=\"330\" y=\"58\" font-size=\"22\">🔔</text>"),
    whatIs: "訊息中心是你在 Agent School 的收件匣，把所有找你的通知都集中在同一頁，不用怕漏接重要消息。從系統發的歡迎與學員編號通知、老師對直播課的提醒、你申請任務後的審核進度，到其他同學主動私訊你討論 Agent，全都依時間排好放在這裡。它幫你一眼分清楚誰找你、為了什麼事，哪些還沒看，讓你專心學習與接案，不必到處翻找。",
    features: [{"icon":"📬","text":"四類通知集中：系統、老師、任務系統、同學私訊都收在一頁"},{"icon":"🔴","text":"右上角未讀計數，告訴你還有幾則沒看（目前 2 則）"},{"icon":"✨","text":"未讀訊息有發光外框與閃爍小圓點，一眼就認得出來"},{"icon":"📋","text":"任務系統回報你申請的任務審核進度，例如電商客服 Agent 審核中"},{"icon":"💬","text":"同學可以私訊你，互相交流 Agent 的技能組合做法"}],
    steps: [{"icon":"👀","title":"看未讀數","desc":"先瞄右上角的未讀標籤，知道有幾則新消息"},{"icon":"📜","title":"由上往下讀","desc":"訊息依時間排列，發光卡片就是還沒看的重點"},{"icon":"🎯","title":"認頭像分類別","desc":"頭像首字幫你分清系統、老師、任務或同學"},{"icon":"🤝","title":"回應互動","desc":"看到同學提問或任務進度，接著去對應功能行動"}],
    voice: "歡迎來到訊息中心，這裡就像你在 Agent School 的專屬收件匣，把所有找你的通知都集中在這一頁，再也不用擔心漏掉重要消息。你看右上角這個標籤，會清楚告訴你現在還有幾則沒看的未讀訊息。下面這些卡片是依照時間排好的，每一則左邊都有一個圓形頭像，上面的字幫你分辨它是誰發來的。最上面通常是系統通知，像是歡迎你加入、給你學員編號；接著是老師的提醒，比如直播課前要先安裝哪些工具；再來是任務系統，它會回報你申請的任務審核到哪一步，例如電商客服 Agent 還在審核中。如果有同學對你的 Agent 感興趣，也會在這裡私訊你交流技能組合。只要看到卡片有發光的外框，還有旁邊閃爍的小圓點，那就代表這則還沒讀過，記得優先看一下，再決定接著去哪個功能行動。",
  },
  "/support": {
    emoji: "🛎️",
    title: "服務中心",
    tagline: "學習路上有疑問，線上提問加常見問答一站搞定",
    svg: scene("<rect x=\"48\" y=\"40\" width=\"180\" height=\"120\" rx=\"14\" fill=\"#fff\" opacity=\"0.06\" stroke=\"#a855f7\" stroke-opacity=\"0.35\"/>\n<rect x=\"62\" y=\"56\" width=\"60\" height=\"7\" rx=\"3.5\" fill=\"#fff\" opacity=\"0.55\"/>\n<rect x=\"62\" y=\"74\" width=\"152\" height=\"22\" rx=\"6\" fill=\"#fff\" opacity=\"0.05\" stroke=\"#6366f1\" stroke-opacity=\"0.4\"/>\n<rect x=\"72\" y=\"82\" width=\"70\" height=\"6\" rx=\"3\" fill=\"#fff\" opacity=\"0.4\"/>\n<rect x=\"62\" y=\"104\" width=\"152\" height=\"38\" rx=\"6\" fill=\"#fff\" opacity=\"0.05\" stroke=\"#6366f1\" stroke-opacity=\"0.35\"/>\n<rect x=\"72\" y=\"112\" width=\"120\" height=\"5\" rx=\"2.5\" fill=\"#fff\" opacity=\"0.35\"/>\n<rect x=\"72\" y=\"123\" width=\"100\" height=\"5\" rx=\"2.5\" fill=\"#fff\" opacity=\"0.25\"/>\n<rect x=\"138\" y=\"148\" width=\"76\" height=\"22\" rx=\"11\" fill=\"url(#pp)\"/>\n<rect x=\"156\" y=\"156\" width=\"40\" height=\"6\" rx=\"3\" fill=\"#fff\" opacity=\"0.95\"/>\n<text x=\"64\" y=\"38\" font-size=\"17\">✍️</text>\n<rect x=\"252\" y=\"52\" width=\"118\" height=\"26\" rx=\"8\" fill=\"#fff\" opacity=\"0.06\" stroke=\"#22d3ee\" stroke-opacity=\"0.4\"/>\n<rect x=\"264\" y=\"62\" width=\"62\" height=\"6\" rx=\"3\" fill=\"#fff\" opacity=\"0.5\"/>\n<path d=\"M349 62 l5 6 5 -6\" stroke=\"#22d3ee\" stroke-width=\"2.4\" fill=\"none\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<rect x=\"252\" y=\"86\" width=\"118\" height=\"26\" rx=\"8\" fill=\"#fff\" opacity=\"0.06\" stroke=\"#22d3ee\" stroke-opacity=\"0.3\"/>\n<rect x=\"264\" y=\"96\" width=\"74\" height=\"6\" rx=\"3\" fill=\"#fff\" opacity=\"0.45\"/>\n<path d=\"M349 96 l5 6 5 -6\" stroke=\"#22d3ee\" stroke-width=\"2.4\" fill=\"none\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<rect x=\"252\" y=\"120\" width=\"118\" height=\"26\" rx=\"8\" fill=\"url(#bl)\" opacity=\"0.85\"/>\n<rect x=\"264\" y=\"130\" width=\"52\" height=\"6\" rx=\"3\" fill=\"#fff\" opacity=\"0.9\"/>\n<path d=\"M349 137 l5 -6 5 6\" stroke=\"#fff\" stroke-width=\"2.4\" fill=\"none\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<rect x=\"252\" y=\"148\" width=\"118\" height=\"22\" rx=\"8\" fill=\"#fff\" opacity=\"0.05\" stroke=\"#22d3ee\" stroke-opacity=\"0.25\"/>\n<rect x=\"264\" y=\"157\" width=\"58\" height=\"5\" rx=\"2.5\" fill=\"#fff\" opacity=\"0.4\"/>\n<text x=\"318\" y=\"44\" font-size=\"17\">❓</text>"),
    whatIs: "服務中心是你在 Agent School 學習、訓練、接案路上卡關時的求助站。不管是不會報名課程、搞不懂技能包怎麼裝、還是點數怎麼累積，這裡都能找到答案。你可以直接填線上提問表單把問題丟給客服，也能先翻翻下面的常見問答自助解決，省下等回覆的時間。簡單講，它讓你遇到問題時不再卡住、不用亂找，安心把心思放回學習本身。",
    features: [{"icon":"✍️","text":"線上提問表單：選問題類型、填主旨與內容描述，一鍵送出"},{"icon":"🏷️","text":"七種問題分類：課程內容、Agent 訓練所、帳號登入、點數兌換、活動報名、合作商務、其他"},{"icon":"❓","text":"六則常見問答，點一下展開答案，涵蓋報名、錄播、配置貼平台、技能包安裝、點數、接案"},{"icon":"🕙","text":"明列客服時間（週一至週五 10:00–18:00）與信箱 support@agentschool.ai"},{"icon":"⏱️","text":"承諾 1–2 個工作天內回覆，送出後按鈕即時顯示已送出"}],
    steps: [{"icon":"❓","title":"先翻常見問答","desc":"點開下方 FAQ，多數疑問都能當場自助解決"},{"icon":"🏷️","title":"選問題類型","desc":"找不到答案就在線上提問選對應的分類"},{"icon":"📝","title":"填主旨與描述","desc":"簡述主旨、詳細說明你遇到的狀況"},{"icon":"📤","title":"送出等回覆","desc":"按送出提問，客服 1–2 個工作天內回你"}],
    voice: "歡迎來到服務中心，這裡是你在 Agent School 遇到任何疑問時的求助站。整頁分成兩個部分，上面是線上提問，下面是常見問答。建議你卡關時先看下面的常見問答，這裡整理了六則最多人問的問題，像是怎麼報名課程、直播能不能錄播回看、Agent 訓練所生成的設定能貼到哪些平台、技能包怎麼安裝、點數怎麼累積，還有怎麼申請接案任務。每一題點一下就會展開答案，多數狀況都能當場自己解決。如果還是找不到答案，就用上面的線上提問。你先在問題類型挑一個分類，像是課程內容、帳號登入或點數兌換，接著填寫主旨，再把遇到的狀況詳細描述清楚，最後按下送出提問就完成了。我們的客服時間是週一到週五早上十點到晚上六點，會在一到兩個工作天內回覆你，也可以直接寫信到 support@agentschool.ai。有問題別憋著，把它交給我們，你只要專心學習就好。",
  },
};
